/*
 * This file is generated by jOOQ.
 */
package stroom.shapeshifter.ai.impl.db.jooq;


import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;

import stroom.shapeshifter.ai.impl.db.jooq.tables.ShapeshifterFeedState;
import stroom.shapeshifter.ai.impl.db.jooq.tables.ShapeshifterLedger;
import stroom.shapeshifter.ai.impl.db.jooq.tables.ShapeshifterRule;
import stroom.shapeshifter.ai.impl.db.jooq.tables.ShapeshifterShape;
import stroom.shapeshifter.ai.impl.db.jooq.tables.ShapeshifterSpend;
import stroom.shapeshifter.ai.impl.db.jooq.tables.records.ShapeshifterFeedStateRecord;
import stroom.shapeshifter.ai.impl.db.jooq.tables.records.ShapeshifterLedgerRecord;
import stroom.shapeshifter.ai.impl.db.jooq.tables.records.ShapeshifterRuleRecord;
import stroom.shapeshifter.ai.impl.db.jooq.tables.records.ShapeshifterShapeRecord;
import stroom.shapeshifter.ai.impl.db.jooq.tables.records.ShapeshifterSpendRecord;


/**
 * A class modelling foreign key relationships and constraints of tables in
 * stroom.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<ShapeshifterFeedStateRecord> KEY_SHAPESHIFTER_FEED_STATE_PRIMARY = Internal.createUniqueKey(ShapeshifterFeedState.SHAPESHIFTER_FEED_STATE, DSL.name("KEY_shapeshifter_feed_state_PRIMARY"), new TableField[] { ShapeshifterFeedState.SHAPESHIFTER_FEED_STATE.ID }, true);
    public static final UniqueKey<ShapeshifterFeedStateRecord> KEY_SHAPESHIFTER_FEED_STATE_SHAPESHIFTER_FEED_STATE_DOC_UUID_FEED_NAME = Internal.createUniqueKey(ShapeshifterFeedState.SHAPESHIFTER_FEED_STATE, DSL.name("KEY_shapeshifter_feed_state_shapeshifter_feed_state_doc_uuid_feed_name"), new TableField[] { ShapeshifterFeedState.SHAPESHIFTER_FEED_STATE.DOC_UUID, ShapeshifterFeedState.SHAPESHIFTER_FEED_STATE.FEED_NAME }, true);
    public static final UniqueKey<ShapeshifterLedgerRecord> KEY_SHAPESHIFTER_LEDGER_PRIMARY = Internal.createUniqueKey(ShapeshifterLedger.SHAPESHIFTER_LEDGER, DSL.name("KEY_shapeshifter_ledger_PRIMARY"), new TableField[] { ShapeshifterLedger.SHAPESHIFTER_LEDGER.ID }, true);
    public static final UniqueKey<ShapeshifterRuleRecord> KEY_SHAPESHIFTER_RULE_PRIMARY = Internal.createUniqueKey(ShapeshifterRule.SHAPESHIFTER_RULE, DSL.name("KEY_shapeshifter_rule_PRIMARY"), new TableField[] { ShapeshifterRule.SHAPESHIFTER_RULE.ID }, true);
    public static final UniqueKey<ShapeshifterRuleRecord> KEY_SHAPESHIFTER_RULE_SHAPESHIFTER_RULE_DOC_UUID_RULE_UUID = Internal.createUniqueKey(ShapeshifterRule.SHAPESHIFTER_RULE, DSL.name("KEY_shapeshifter_rule_shapeshifter_rule_doc_uuid_rule_uuid"), new TableField[] { ShapeshifterRule.SHAPESHIFTER_RULE.DOC_UUID, ShapeshifterRule.SHAPESHIFTER_RULE.RULE_UUID }, true);
    public static final UniqueKey<ShapeshifterShapeRecord> KEY_SHAPESHIFTER_SHAPE_PRIMARY = Internal.createUniqueKey(ShapeshifterShape.SHAPESHIFTER_SHAPE, DSL.name("KEY_shapeshifter_shape_PRIMARY"), new TableField[] { ShapeshifterShape.SHAPESHIFTER_SHAPE.ID }, true);
    public static final UniqueKey<ShapeshifterShapeRecord> KEY_SHAPESHIFTER_SHAPE_SHAPESHIFTER_SHAPE_DOC_UUID_SHAPE_ID = Internal.createUniqueKey(ShapeshifterShape.SHAPESHIFTER_SHAPE, DSL.name("KEY_shapeshifter_shape_shapeshifter_shape_doc_uuid_shape_id"), new TableField[] { ShapeshifterShape.SHAPESHIFTER_SHAPE.DOC_UUID, ShapeshifterShape.SHAPESHIFTER_SHAPE.SHAPE_ID }, true);
    public static final UniqueKey<ShapeshifterSpendRecord> KEY_SHAPESHIFTER_SPEND_PRIMARY = Internal.createUniqueKey(ShapeshifterSpend.SHAPESHIFTER_SPEND, DSL.name("KEY_shapeshifter_spend_PRIMARY"), new TableField[] { ShapeshifterSpend.SHAPESHIFTER_SPEND.ID }, true);
    public static final UniqueKey<ShapeshifterSpendRecord> KEY_SHAPESHIFTER_SPEND_SHAPESHIFTER_SPEND_DOC_UUID = Internal.createUniqueKey(ShapeshifterSpend.SHAPESHIFTER_SPEND, DSL.name("KEY_shapeshifter_spend_shapeshifter_spend_doc_uuid"), new TableField[] { ShapeshifterSpend.SHAPESHIFTER_SPEND.DOC_UUID }, true);
}
