/*
 * This file is generated by jOOQ.
 */
package stroom.shapeshifter.ai.impl.db.jooq;


import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.DSL;
import org.jooq.impl.SchemaImpl;

import stroom.shapeshifter.ai.impl.db.jooq.tables.ShapeshifterAttempt;
import stroom.shapeshifter.ai.impl.db.jooq.tables.ShapeshifterFeedState;
import stroom.shapeshifter.ai.impl.db.jooq.tables.ShapeshifterLedger;
import stroom.shapeshifter.ai.impl.db.jooq.tables.ShapeshifterRule;
import stroom.shapeshifter.ai.impl.db.jooq.tables.ShapeshifterShape;
import stroom.shapeshifter.ai.impl.db.jooq.tables.ShapeshifterSpend;
import stroom.shapeshifter.ai.impl.db.jooq.tables.ShapeshifterTurn;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Stroom extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>stroom</code>
     */
    public static final Stroom STROOM = new Stroom();

    /**
     * The table <code>stroom.shapeshifter_attempt</code>.
     */
    public final ShapeshifterAttempt SHAPESHIFTER_ATTEMPT = ShapeshifterAttempt.SHAPESHIFTER_ATTEMPT;

    /**
     * The table <code>stroom.shapeshifter_feed_state</code>.
     */
    public final ShapeshifterFeedState SHAPESHIFTER_FEED_STATE = ShapeshifterFeedState.SHAPESHIFTER_FEED_STATE;

    /**
     * The table <code>stroom.shapeshifter_ledger</code>.
     */
    public final ShapeshifterLedger SHAPESHIFTER_LEDGER = ShapeshifterLedger.SHAPESHIFTER_LEDGER;

    /**
     * The table <code>stroom.shapeshifter_rule</code>.
     */
    public final ShapeshifterRule SHAPESHIFTER_RULE = ShapeshifterRule.SHAPESHIFTER_RULE;

    /**
     * The table <code>stroom.shapeshifter_shape</code>.
     */
    public final ShapeshifterShape SHAPESHIFTER_SHAPE = ShapeshifterShape.SHAPESHIFTER_SHAPE;

    /**
     * The table <code>stroom.shapeshifter_spend</code>.
     */
    public final ShapeshifterSpend SHAPESHIFTER_SPEND = ShapeshifterSpend.SHAPESHIFTER_SPEND;

    /**
     * The table <code>stroom.shapeshifter_turn</code>.
     */
    public final ShapeshifterTurn SHAPESHIFTER_TURN = ShapeshifterTurn.SHAPESHIFTER_TURN;

    /**
     * No further instances allowed
     */
    private Stroom() {
        super(DSL.name("stroom"), null, DSL.comment(""));
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            ShapeshifterAttempt.SHAPESHIFTER_ATTEMPT,
            ShapeshifterFeedState.SHAPESHIFTER_FEED_STATE,
            ShapeshifterLedger.SHAPESHIFTER_LEDGER,
            ShapeshifterRule.SHAPESHIFTER_RULE,
            ShapeshifterShape.SHAPESHIFTER_SHAPE,
            ShapeshifterSpend.SHAPESHIFTER_SPEND,
            ShapeshifterTurn.SHAPESHIFTER_TURN
        );
    }
}
