/*
 * This file is generated by jOOQ.
 */
package stroom.shapeshifter.ai.impl.db.jooq;


import stroom.shapeshifter.ai.impl.db.jooq.tables.ShapeshifterAttempt;
import stroom.shapeshifter.ai.impl.db.jooq.tables.ShapeshifterFeedState;
import stroom.shapeshifter.ai.impl.db.jooq.tables.ShapeshifterGuidance;
import stroom.shapeshifter.ai.impl.db.jooq.tables.ShapeshifterLedger;
import stroom.shapeshifter.ai.impl.db.jooq.tables.ShapeshifterOutput;
import stroom.shapeshifter.ai.impl.db.jooq.tables.ShapeshifterRule;
import stroom.shapeshifter.ai.impl.db.jooq.tables.ShapeshifterShape;
import stroom.shapeshifter.ai.impl.db.jooq.tables.ShapeshifterSpend;
import stroom.shapeshifter.ai.impl.db.jooq.tables.ShapeshifterTurn;


/**
 * Convenience access to all tables in stroom.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * The table <code>stroom.shapeshifter_attempt</code>.
     */
    public static final ShapeshifterAttempt SHAPESHIFTER_ATTEMPT = ShapeshifterAttempt.SHAPESHIFTER_ATTEMPT;

    /**
     * The table <code>stroom.shapeshifter_feed_state</code>.
     */
    public static final ShapeshifterFeedState SHAPESHIFTER_FEED_STATE = ShapeshifterFeedState.SHAPESHIFTER_FEED_STATE;

    /**
     * The table <code>stroom.shapeshifter_guidance</code>.
     */
    public static final ShapeshifterGuidance SHAPESHIFTER_GUIDANCE = ShapeshifterGuidance.SHAPESHIFTER_GUIDANCE;

    /**
     * The table <code>stroom.shapeshifter_ledger</code>.
     */
    public static final ShapeshifterLedger SHAPESHIFTER_LEDGER = ShapeshifterLedger.SHAPESHIFTER_LEDGER;

    /**
     * The table <code>stroom.shapeshifter_output</code>.
     */
    public static final ShapeshifterOutput SHAPESHIFTER_OUTPUT = ShapeshifterOutput.SHAPESHIFTER_OUTPUT;

    /**
     * The table <code>stroom.shapeshifter_rule</code>.
     */
    public static final ShapeshifterRule SHAPESHIFTER_RULE = ShapeshifterRule.SHAPESHIFTER_RULE;

    /**
     * The table <code>stroom.shapeshifter_shape</code>.
     */
    public static final ShapeshifterShape SHAPESHIFTER_SHAPE = ShapeshifterShape.SHAPESHIFTER_SHAPE;

    /**
     * The table <code>stroom.shapeshifter_spend</code>.
     */
    public static final ShapeshifterSpend SHAPESHIFTER_SPEND = ShapeshifterSpend.SHAPESHIFTER_SPEND;

    /**
     * The table <code>stroom.shapeshifter_turn</code>.
     */
    public static final ShapeshifterTurn SHAPESHIFTER_TURN = ShapeshifterTurn.SHAPESHIFTER_TURN;
}
