/*
 * This file is generated by jOOQ.
 */
package stroom.shapeshifter.ai.impl.db.jooq;


import stroom.shapeshifter.ai.impl.db.jooq.tables.ShapeshifterFeedState;
import stroom.shapeshifter.ai.impl.db.jooq.tables.ShapeshifterLedger;
import stroom.shapeshifter.ai.impl.db.jooq.tables.ShapeshifterRule;
import stroom.shapeshifter.ai.impl.db.jooq.tables.ShapeshifterShape;
import stroom.shapeshifter.ai.impl.db.jooq.tables.ShapeshifterSpend;


/**
 * Convenience access to all tables in stroom.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * The table <code>stroom.shapeshifter_feed_state</code>.
     */
    public static final ShapeshifterFeedState SHAPESHIFTER_FEED_STATE = ShapeshifterFeedState.SHAPESHIFTER_FEED_STATE;

    /**
     * The table <code>stroom.shapeshifter_ledger</code>.
     */
    public static final ShapeshifterLedger SHAPESHIFTER_LEDGER = ShapeshifterLedger.SHAPESHIFTER_LEDGER;

    /**
     * The table <code>stroom.shapeshifter_rule</code>.
     */
    public static final ShapeshifterRule SHAPESHIFTER_RULE = ShapeshifterRule.SHAPESHIFTER_RULE;

    /**
     * The table <code>stroom.shapeshifter_shape</code>.
     */
    public static final ShapeshifterShape SHAPESHIFTER_SHAPE = ShapeshifterShape.SHAPESHIFTER_SHAPE;

    /**
     * The table <code>stroom.shapeshifter_spend</code>.
     */
    public static final ShapeshifterSpend SHAPESHIFTER_SPEND = ShapeshifterSpend.SHAPESHIFTER_SPEND;
}
