/*
 * This file is generated by jOOQ.
 */
package stroom.shapeshifter.ai.impl.db.jooq.tables;


import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import stroom.shapeshifter.ai.impl.db.jooq.Indexes;
import stroom.shapeshifter.ai.impl.db.jooq.Keys;
import stroom.shapeshifter.ai.impl.db.jooq.Stroom;
import stroom.shapeshifter.ai.impl.db.jooq.tables.records.ShapeshifterAttemptRecord;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ShapeshifterAttempt extends TableImpl<ShapeshifterAttemptRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>stroom.shapeshifter_attempt</code>
     */
    public static final ShapeshifterAttempt SHAPESHIFTER_ATTEMPT = new ShapeshifterAttempt();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ShapeshifterAttemptRecord> getRecordType() {
        return ShapeshifterAttemptRecord.class;
    }

    /**
     * The column <code>stroom.shapeshifter_attempt.id</code>.
     */
    public final TableField<ShapeshifterAttemptRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>stroom.shapeshifter_attempt.version</code>.
     */
    public final TableField<ShapeshifterAttemptRecord, Integer> VERSION = createField(DSL.name("version"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>stroom.shapeshifter_attempt.create_time_ms</code>.
     */
    public final TableField<ShapeshifterAttemptRecord, Long> CREATE_TIME_MS = createField(DSL.name("create_time_ms"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>stroom.shapeshifter_attempt.update_time_ms</code>.
     */
    public final TableField<ShapeshifterAttemptRecord, Long> UPDATE_TIME_MS = createField(DSL.name("update_time_ms"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>stroom.shapeshifter_attempt.doc_uuid</code>.
     */
    public final TableField<ShapeshifterAttemptRecord, String> DOC_UUID = createField(DSL.name("doc_uuid"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>stroom.shapeshifter_attempt.shape_hash</code>.
     */
    public final TableField<ShapeshifterAttemptRecord, String> SHAPE_HASH = createField(DSL.name("shape_hash"), SQLDataType.VARCHAR(64).nullable(false), this, "");

    /**
     * The column <code>stroom.shapeshifter_attempt.shape_id</code>.
     */
    public final TableField<ShapeshifterAttemptRecord, String> SHAPE_ID = createField(DSL.name("shape_id"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>stroom.shapeshifter_attempt.feed_name</code>.
     */
    public final TableField<ShapeshifterAttemptRecord, String> FEED_NAME = createField(DSL.name("feed_name"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>stroom.shapeshifter_attempt.type_name</code>.
     */
    public final TableField<ShapeshifterAttemptRecord, String> TYPE_NAME = createField(DSL.name("type_name"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>stroom.shapeshifter_attempt.input_meta_id</code>.
     */
    public final TableField<ShapeshifterAttemptRecord, Long> INPUT_META_ID = createField(DSL.name("input_meta_id"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>stroom.shapeshifter_attempt.node_name</code>.
     */
    public final TableField<ShapeshifterAttemptRecord, String> NODE_NAME = createField(DSL.name("node_name"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>stroom.shapeshifter_attempt.execution_mode</code>.
     */
    public final TableField<ShapeshifterAttemptRecord, String> EXECUTION_MODE = createField(DSL.name("execution_mode"), SQLDataType.VARCHAR(32).nullable(false), this, "");

    /**
     * The column <code>stroom.shapeshifter_attempt.promotion_mode</code>.
     */
    public final TableField<ShapeshifterAttemptRecord, String> PROMOTION_MODE = createField(DSL.name("promotion_mode"), SQLDataType.VARCHAR(32).nullable(false), this, "");

    /**
     * The column <code>stroom.shapeshifter_attempt.status</code>.
     */
    public final TableField<ShapeshifterAttemptRecord, String> STATUS = createField(DSL.name("status"), SQLDataType.VARCHAR(32).nullable(false), this, "");

    /**
     * The column <code>stroom.shapeshifter_attempt.decision</code>.
     */
    public final TableField<ShapeshifterAttemptRecord, String> DECISION = createField(DSL.name("decision"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>stroom.shapeshifter_attempt.rule_uuid</code>.
     */
    public final TableField<ShapeshifterAttemptRecord, String> RULE_UUID = createField(DSL.name("rule_uuid"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>stroom.shapeshifter_attempt.score</code>.
     */
    public final TableField<ShapeshifterAttemptRecord, Double> SCORE = createField(DSL.name("score"), SQLDataType.DOUBLE, this, "");

    /**
     * The column <code>stroom.shapeshifter_attempt.tokens_spent</code>.
     */
    public final TableField<ShapeshifterAttemptRecord, Long> TOKENS_SPENT = createField(DSL.name("tokens_spent"), SQLDataType.BIGINT.nullable(false).defaultValue(DSL.inline("0", SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>stroom.shapeshifter_attempt.expiry_ms</code>.
     */
    public final TableField<ShapeshifterAttemptRecord, Long> EXPIRY_MS = createField(DSL.name("expiry_ms"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>stroom.shapeshifter_attempt.claim_key</code>.
     */
    public final TableField<ShapeshifterAttemptRecord, String> CLAIM_KEY = createField(DSL.name("claim_key"), SQLDataType.VARCHAR(64), this, "");

    private ShapeshifterAttempt(Name alias, Table<ShapeshifterAttemptRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private ShapeshifterAttempt(Name alias, Table<ShapeshifterAttemptRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>stroom.shapeshifter_attempt</code> table
     * reference
     */
    public ShapeshifterAttempt(String alias) {
        this(DSL.name(alias), SHAPESHIFTER_ATTEMPT);
    }

    /**
     * Create an aliased <code>stroom.shapeshifter_attempt</code> table
     * reference
     */
    public ShapeshifterAttempt(Name alias) {
        this(alias, SHAPESHIFTER_ATTEMPT);
    }

    /**
     * Create a <code>stroom.shapeshifter_attempt</code> table reference
     */
    public ShapeshifterAttempt() {
        this(DSL.name("shapeshifter_attempt"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Stroom.STROOM;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.SHAPESHIFTER_ATTEMPT_SHAPESHIFTER_ATTEMPT_CREATE_TIME_MS, Indexes.SHAPESHIFTER_ATTEMPT_SHAPESHIFTER_ATTEMPT_DOC_SHAPE, Indexes.SHAPESHIFTER_ATTEMPT_SHAPESHIFTER_ATTEMPT_STATUS);
    }

    @Override
    public Identity<ShapeshifterAttemptRecord, Long> getIdentity() {
        return (Identity<ShapeshifterAttemptRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<ShapeshifterAttemptRecord> getPrimaryKey() {
        return Keys.KEY_SHAPESHIFTER_ATTEMPT_PRIMARY;
    }

    @Override
    public List<UniqueKey<ShapeshifterAttemptRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.KEY_SHAPESHIFTER_ATTEMPT_SHAPESHIFTER_ATTEMPT_CLAIM);
    }

    @Override
    public TableField<ShapeshifterAttemptRecord, Integer> getRecordVersion() {
        return VERSION;
    }

    @Override
    public ShapeshifterAttempt as(String alias) {
        return new ShapeshifterAttempt(DSL.name(alias), this);
    }

    @Override
    public ShapeshifterAttempt as(Name alias) {
        return new ShapeshifterAttempt(alias, this);
    }

    @Override
    public ShapeshifterAttempt as(Table<?> alias) {
        return new ShapeshifterAttempt(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public ShapeshifterAttempt rename(String name) {
        return new ShapeshifterAttempt(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public ShapeshifterAttempt rename(Name name) {
        return new ShapeshifterAttempt(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public ShapeshifterAttempt rename(Table<?> name) {
        return new ShapeshifterAttempt(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ShapeshifterAttempt where(Condition condition) {
        return new ShapeshifterAttempt(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ShapeshifterAttempt where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ShapeshifterAttempt where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ShapeshifterAttempt where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ShapeshifterAttempt where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ShapeshifterAttempt where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ShapeshifterAttempt where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ShapeshifterAttempt where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ShapeshifterAttempt whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ShapeshifterAttempt whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
