/*
 * This file is generated by jOOQ.
 */
package stroom.shapeshifter.ai.impl.db.jooq.tables;


import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import stroom.shapeshifter.ai.impl.db.jooq.Keys;
import stroom.shapeshifter.ai.impl.db.jooq.Stroom;
import stroom.shapeshifter.ai.impl.db.jooq.tables.records.ShapeshifterTurnRecord;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ShapeshifterTurn extends TableImpl<ShapeshifterTurnRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>stroom.shapeshifter_turn</code>
     */
    public static final ShapeshifterTurn SHAPESHIFTER_TURN = new ShapeshifterTurn();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ShapeshifterTurnRecord> getRecordType() {
        return ShapeshifterTurnRecord.class;
    }

    /**
     * The column <code>stroom.shapeshifter_turn.id</code>.
     */
    public final TableField<ShapeshifterTurnRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>stroom.shapeshifter_turn.create_time_ms</code>.
     */
    public final TableField<ShapeshifterTurnRecord, Long> CREATE_TIME_MS = createField(DSL.name("create_time_ms"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>stroom.shapeshifter_turn.fk_attempt_id</code>.
     */
    public final TableField<ShapeshifterTurnRecord, Long> FK_ATTEMPT_ID = createField(DSL.name("fk_attempt_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>stroom.shapeshifter_turn.turn_number</code>.
     */
    public final TableField<ShapeshifterTurnRecord, Integer> TURN_NUMBER = createField(DSL.name("turn_number"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>stroom.shapeshifter_turn.step_id</code>.
     */
    public final TableField<ShapeshifterTurnRecord, String> STEP_ID = createField(DSL.name("step_id"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>stroom.shapeshifter_turn.candidate</code>.
     */
    public final TableField<ShapeshifterTurnRecord, Integer> CANDIDATE = createField(DSL.name("candidate"), SQLDataType.INTEGER.nullable(false).defaultValue(DSL.inline("1", SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>stroom.shapeshifter_turn.question_kind</code>.
     */
    public final TableField<ShapeshifterTurnRecord, String> QUESTION_KIND = createField(DSL.name("question_kind"), SQLDataType.VARCHAR(32).nullable(false), this, "");

    /**
     * The column <code>stroom.shapeshifter_turn.question</code>.
     */
    public final TableField<ShapeshifterTurnRecord, String> QUESTION = createField(DSL.name("question"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>stroom.shapeshifter_turn.answer</code>.
     */
    public final TableField<ShapeshifterTurnRecord, String> ANSWER = createField(DSL.name("answer"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>stroom.shapeshifter_turn.answered_by</code>.
     */
    public final TableField<ShapeshifterTurnRecord, String> ANSWERED_BY = createField(DSL.name("answered_by"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>stroom.shapeshifter_turn.outcome</code>.
     */
    public final TableField<ShapeshifterTurnRecord, String> OUTCOME = createField(DSL.name("outcome"), SQLDataType.VARCHAR(32), this, "");

    private ShapeshifterTurn(Name alias, Table<ShapeshifterTurnRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private ShapeshifterTurn(Name alias, Table<ShapeshifterTurnRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>stroom.shapeshifter_turn</code> table reference
     */
    public ShapeshifterTurn(String alias) {
        this(DSL.name(alias), SHAPESHIFTER_TURN);
    }

    /**
     * Create an aliased <code>stroom.shapeshifter_turn</code> table reference
     */
    public ShapeshifterTurn(Name alias) {
        this(alias, SHAPESHIFTER_TURN);
    }

    /**
     * Create a <code>stroom.shapeshifter_turn</code> table reference
     */
    public ShapeshifterTurn() {
        this(DSL.name("shapeshifter_turn"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Stroom.STROOM;
    }

    @Override
    public Identity<ShapeshifterTurnRecord, Long> getIdentity() {
        return (Identity<ShapeshifterTurnRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<ShapeshifterTurnRecord> getPrimaryKey() {
        return Keys.KEY_SHAPESHIFTER_TURN_PRIMARY;
    }

    @Override
    public List<UniqueKey<ShapeshifterTurnRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.KEY_SHAPESHIFTER_TURN_SHAPESHIFTER_TURN_ATTEMPT_TURN);
    }

    @Override
    public List<ForeignKey<ShapeshifterTurnRecord, ?>> getReferences() {
        return Arrays.asList(Keys.SHAPESHIFTER_TURN_ATTEMPT_FK);
    }

    @Override
    public ShapeshifterTurn as(String alias) {
        return new ShapeshifterTurn(DSL.name(alias), this);
    }

    @Override
    public ShapeshifterTurn as(Name alias) {
        return new ShapeshifterTurn(alias, this);
    }

    @Override
    public ShapeshifterTurn as(Table<?> alias) {
        return new ShapeshifterTurn(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public ShapeshifterTurn rename(String name) {
        return new ShapeshifterTurn(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public ShapeshifterTurn rename(Name name) {
        return new ShapeshifterTurn(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public ShapeshifterTurn rename(Table<?> name) {
        return new ShapeshifterTurn(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ShapeshifterTurn where(Condition condition) {
        return new ShapeshifterTurn(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ShapeshifterTurn where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ShapeshifterTurn where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ShapeshifterTurn where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ShapeshifterTurn where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ShapeshifterTurn where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ShapeshifterTurn where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ShapeshifterTurn where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ShapeshifterTurn whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ShapeshifterTurn whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
