/*
 * This file is generated by jOOQ.
 */
package stroom.shapeshifter.ai.impl.db.jooq.tables;


import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import stroom.shapeshifter.ai.impl.db.jooq.Keys;
import stroom.shapeshifter.ai.impl.db.jooq.Stroom;
import stroom.shapeshifter.ai.impl.db.jooq.tables.records.ShapeshifterFeedStateRecord;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ShapeshifterFeedState extends TableImpl<ShapeshifterFeedStateRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>stroom.shapeshifter_feed_state</code>
     */
    public static final ShapeshifterFeedState SHAPESHIFTER_FEED_STATE = new ShapeshifterFeedState();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ShapeshifterFeedStateRecord> getRecordType() {
        return ShapeshifterFeedStateRecord.class;
    }

    /**
     * The column <code>stroom.shapeshifter_feed_state.id</code>.
     */
    public final TableField<ShapeshifterFeedStateRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>stroom.shapeshifter_feed_state.version</code>.
     */
    public final TableField<ShapeshifterFeedStateRecord, Integer> VERSION = createField(DSL.name("version"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>stroom.shapeshifter_feed_state.update_time_ms</code>.
     */
    public final TableField<ShapeshifterFeedStateRecord, Long> UPDATE_TIME_MS = createField(DSL.name("update_time_ms"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>stroom.shapeshifter_feed_state.doc_uuid</code>.
     */
    public final TableField<ShapeshifterFeedStateRecord, String> DOC_UUID = createField(DSL.name("doc_uuid"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>stroom.shapeshifter_feed_state.feed_name</code>.
     */
    public final TableField<ShapeshifterFeedStateRecord, String> FEED_NAME = createField(DSL.name("feed_name"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>stroom.shapeshifter_feed_state.failure_streak</code>.
     */
    public final TableField<ShapeshifterFeedStateRecord, Integer> FAILURE_STREAK = createField(DSL.name("failure_streak"), SQLDataType.INTEGER.nullable(false).defaultValue(DSL.inline("0", SQLDataType.INTEGER)), this, "");

    /**
     * The column
     * <code>stroom.shapeshifter_feed_state.error_mode_since_ms</code>.
     */
    public final TableField<ShapeshifterFeedStateRecord, Long> ERROR_MODE_SINCE_MS = createField(DSL.name("error_mode_since_ms"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>stroom.shapeshifter_feed_state.error_mode_reason</code>.
     */
    public final TableField<ShapeshifterFeedStateRecord, String> ERROR_MODE_REASON = createField(DSL.name("error_mode_reason"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>stroom.shapeshifter_feed_state.reset_time_ms</code>.
     */
    public final TableField<ShapeshifterFeedStateRecord, Long> RESET_TIME_MS = createField(DSL.name("reset_time_ms"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>stroom.shapeshifter_feed_state.reset_user</code>.
     */
    public final TableField<ShapeshifterFeedStateRecord, String> RESET_USER = createField(DSL.name("reset_user"), SQLDataType.VARCHAR(255), this, "");

    private ShapeshifterFeedState(Name alias, Table<ShapeshifterFeedStateRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private ShapeshifterFeedState(Name alias, Table<ShapeshifterFeedStateRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>stroom.shapeshifter_feed_state</code> table
     * reference
     */
    public ShapeshifterFeedState(String alias) {
        this(DSL.name(alias), SHAPESHIFTER_FEED_STATE);
    }

    /**
     * Create an aliased <code>stroom.shapeshifter_feed_state</code> table
     * reference
     */
    public ShapeshifterFeedState(Name alias) {
        this(alias, SHAPESHIFTER_FEED_STATE);
    }

    /**
     * Create a <code>stroom.shapeshifter_feed_state</code> table reference
     */
    public ShapeshifterFeedState() {
        this(DSL.name("shapeshifter_feed_state"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Stroom.STROOM;
    }

    @Override
    public Identity<ShapeshifterFeedStateRecord, Long> getIdentity() {
        return (Identity<ShapeshifterFeedStateRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<ShapeshifterFeedStateRecord> getPrimaryKey() {
        return Keys.KEY_SHAPESHIFTER_FEED_STATE_PRIMARY;
    }

    @Override
    public List<UniqueKey<ShapeshifterFeedStateRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.KEY_SHAPESHIFTER_FEED_STATE_SHAPESHIFTER_FEED_STATE_DOC_UUID_FEED_NAME);
    }

    @Override
    public TableField<ShapeshifterFeedStateRecord, Integer> getRecordVersion() {
        return VERSION;
    }

    @Override
    public ShapeshifterFeedState as(String alias) {
        return new ShapeshifterFeedState(DSL.name(alias), this);
    }

    @Override
    public ShapeshifterFeedState as(Name alias) {
        return new ShapeshifterFeedState(alias, this);
    }

    @Override
    public ShapeshifterFeedState as(Table<?> alias) {
        return new ShapeshifterFeedState(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public ShapeshifterFeedState rename(String name) {
        return new ShapeshifterFeedState(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public ShapeshifterFeedState rename(Name name) {
        return new ShapeshifterFeedState(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public ShapeshifterFeedState rename(Table<?> name) {
        return new ShapeshifterFeedState(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ShapeshifterFeedState where(Condition condition) {
        return new ShapeshifterFeedState(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ShapeshifterFeedState where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ShapeshifterFeedState where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ShapeshifterFeedState where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ShapeshifterFeedState where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ShapeshifterFeedState where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ShapeshifterFeedState where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ShapeshifterFeedState where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ShapeshifterFeedState whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ShapeshifterFeedState whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
