/*
 * This file is generated by jOOQ.
 */
package stroom.shapeshifter.ai.impl.db.jooq.tables;


import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import stroom.shapeshifter.ai.impl.db.jooq.Indexes;
import stroom.shapeshifter.ai.impl.db.jooq.Keys;
import stroom.shapeshifter.ai.impl.db.jooq.Stroom;
import stroom.shapeshifter.ai.impl.db.jooq.tables.records.ShapeshifterOutputRecord;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ShapeshifterOutput extends TableImpl<ShapeshifterOutputRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>stroom.shapeshifter_output</code>
     */
    public static final ShapeshifterOutput SHAPESHIFTER_OUTPUT = new ShapeshifterOutput();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ShapeshifterOutputRecord> getRecordType() {
        return ShapeshifterOutputRecord.class;
    }

    /**
     * The column <code>stroom.shapeshifter_output.id</code>.
     */
    public final TableField<ShapeshifterOutputRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>stroom.shapeshifter_output.create_time_ms</code>.
     */
    public final TableField<ShapeshifterOutputRecord, Long> CREATE_TIME_MS = createField(DSL.name("create_time_ms"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>stroom.shapeshifter_output.doc_uuid</code>.
     */
    public final TableField<ShapeshifterOutputRecord, String> DOC_UUID = createField(DSL.name("doc_uuid"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>stroom.shapeshifter_output.rule_uuid</code>.
     */
    public final TableField<ShapeshifterOutputRecord, String> RULE_UUID = createField(DSL.name("rule_uuid"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>stroom.shapeshifter_output.input_meta_id</code>.
     */
    public final TableField<ShapeshifterOutputRecord, Long> INPUT_META_ID = createField(DSL.name("input_meta_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>stroom.shapeshifter_output.pipeline_uuid</code>.
     */
    public final TableField<ShapeshifterOutputRecord, String> PIPELINE_UUID = createField(DSL.name("pipeline_uuid"), SQLDataType.VARCHAR(255).nullable(false).defaultValue(DSL.inline("", SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>stroom.shapeshifter_output.fragment_uuid</code>.
     */
    public final TableField<ShapeshifterOutputRecord, String> FRAGMENT_UUID = createField(DSL.name("fragment_uuid"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>stroom.shapeshifter_output.provisional</code>.
     */
    public final TableField<ShapeshifterOutputRecord, Boolean> PROVISIONAL = createField(DSL.name("provisional"), SQLDataType.BOOLEAN.nullable(false).defaultValue(DSL.inline("0", SQLDataType.BOOLEAN)), this, "");

    /**
     * The column <code>stroom.shapeshifter_output.score</code>.
     */
    public final TableField<ShapeshifterOutputRecord, Double> SCORE = createField(DSL.name("score"), SQLDataType.DOUBLE, this, "");

    /**
     * The column <code>stroom.shapeshifter_output.boundary_element</code>.
     */
    public final TableField<ShapeshifterOutputRecord, String> BOUNDARY_ELEMENT = createField(DSL.name("boundary_element"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>stroom.shapeshifter_output.boundary_array</code>.
     */
    public final TableField<ShapeshifterOutputRecord, String> BOUNDARY_ARRAY = createField(DSL.name("boundary_array"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>stroom.shapeshifter_output.boundary_depth</code>.
     */
    public final TableField<ShapeshifterOutputRecord, Integer> BOUNDARY_DEPTH = createField(DSL.name("boundary_depth"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>stroom.shapeshifter_output.produce_time_ms</code>.
     */
    public final TableField<ShapeshifterOutputRecord, Long> PRODUCE_TIME_MS = createField(DSL.name("produce_time_ms"), SQLDataType.BIGINT.nullable(false).defaultValue(DSL.inline("0", SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>stroom.shapeshifter_output.record_spans</code>.
     */
    public final TableField<ShapeshifterOutputRecord, String> RECORD_SPANS = createField(DSL.name("record_spans"), SQLDataType.CLOB(16777215), this, "");

    private ShapeshifterOutput(Name alias, Table<ShapeshifterOutputRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private ShapeshifterOutput(Name alias, Table<ShapeshifterOutputRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>stroom.shapeshifter_output</code> table reference
     */
    public ShapeshifterOutput(String alias) {
        this(DSL.name(alias), SHAPESHIFTER_OUTPUT);
    }

    /**
     * Create an aliased <code>stroom.shapeshifter_output</code> table reference
     */
    public ShapeshifterOutput(Name alias) {
        this(alias, SHAPESHIFTER_OUTPUT);
    }

    /**
     * Create a <code>stroom.shapeshifter_output</code> table reference
     */
    public ShapeshifterOutput() {
        this(DSL.name("shapeshifter_output"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Stroom.STROOM;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.SHAPESHIFTER_OUTPUT_SHAPESHIFTER_OUTPUT_DOC_UUID);
    }

    @Override
    public Identity<ShapeshifterOutputRecord, Long> getIdentity() {
        return (Identity<ShapeshifterOutputRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<ShapeshifterOutputRecord> getPrimaryKey() {
        return Keys.KEY_SHAPESHIFTER_OUTPUT_PRIMARY;
    }

    @Override
    public List<UniqueKey<ShapeshifterOutputRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.KEY_SHAPESHIFTER_OUTPUT_SHAPESHIFTER_OUTPUT_RULE_INPUT_PIPELINE);
    }

    @Override
    public ShapeshifterOutput as(String alias) {
        return new ShapeshifterOutput(DSL.name(alias), this);
    }

    @Override
    public ShapeshifterOutput as(Name alias) {
        return new ShapeshifterOutput(alias, this);
    }

    @Override
    public ShapeshifterOutput as(Table<?> alias) {
        return new ShapeshifterOutput(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public ShapeshifterOutput rename(String name) {
        return new ShapeshifterOutput(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public ShapeshifterOutput rename(Name name) {
        return new ShapeshifterOutput(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public ShapeshifterOutput rename(Table<?> name) {
        return new ShapeshifterOutput(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ShapeshifterOutput where(Condition condition) {
        return new ShapeshifterOutput(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ShapeshifterOutput where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ShapeshifterOutput where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ShapeshifterOutput where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ShapeshifterOutput where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ShapeshifterOutput where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ShapeshifterOutput where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ShapeshifterOutput where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ShapeshifterOutput whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ShapeshifterOutput whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
