/*
 * This file is generated by jOOQ.
 */
package stroom.shapeshifter.ai.impl.db.jooq.tables;


import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import stroom.shapeshifter.ai.impl.db.jooq.Keys;
import stroom.shapeshifter.ai.impl.db.jooq.Stroom;
import stroom.shapeshifter.ai.impl.db.jooq.tables.records.ShapeshifterShapeRecord;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ShapeshifterShape extends TableImpl<ShapeshifterShapeRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>stroom.shapeshifter_shape</code>
     */
    public static final ShapeshifterShape SHAPESHIFTER_SHAPE = new ShapeshifterShape();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ShapeshifterShapeRecord> getRecordType() {
        return ShapeshifterShapeRecord.class;
    }

    /**
     * The column <code>stroom.shapeshifter_shape.id</code>.
     */
    public final TableField<ShapeshifterShapeRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>stroom.shapeshifter_shape.version</code>.
     */
    public final TableField<ShapeshifterShapeRecord, Integer> VERSION = createField(DSL.name("version"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>stroom.shapeshifter_shape.create_time_ms</code>.
     */
    public final TableField<ShapeshifterShapeRecord, Long> CREATE_TIME_MS = createField(DSL.name("create_time_ms"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>stroom.shapeshifter_shape.update_time_ms</code>.
     */
    public final TableField<ShapeshifterShapeRecord, Long> UPDATE_TIME_MS = createField(DSL.name("update_time_ms"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>stroom.shapeshifter_shape.doc_uuid</code>.
     */
    public final TableField<ShapeshifterShapeRecord, String> DOC_UUID = createField(DSL.name("doc_uuid"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>stroom.shapeshifter_shape.shape_hash</code>.
     */
    public final TableField<ShapeshifterShapeRecord, String> SHAPE_HASH = createField(DSL.name("shape_hash"), SQLDataType.VARCHAR(64).nullable(false), this, "");

    /**
     * The column <code>stroom.shapeshifter_shape.shape_id</code>.
     */
    public final TableField<ShapeshifterShapeRecord, String> SHAPE_ID = createField(DSL.name("shape_id"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>stroom.shapeshifter_shape.given_up_reason</code>.
     */
    public final TableField<ShapeshifterShapeRecord, String> GIVEN_UP_REASON = createField(DSL.name("given_up_reason"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>stroom.shapeshifter_shape.relearn_reason</code>.
     */
    public final TableField<ShapeshifterShapeRecord, String> RELEARN_REASON = createField(DSL.name("relearn_reason"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>stroom.shapeshifter_shape.awaiting_rule_uuid</code>.
     */
    public final TableField<ShapeshifterShapeRecord, String> AWAITING_RULE_UUID = createField(DSL.name("awaiting_rule_uuid"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>stroom.shapeshifter_shape.rolling_score</code>.
     */
    public final TableField<ShapeshifterShapeRecord, Double> ROLLING_SCORE = createField(DSL.name("rolling_score"), SQLDataType.DOUBLE, this, "");

    /**
     * The column <code>stroom.shapeshifter_shape.rolling_records</code>.
     */
    public final TableField<ShapeshifterShapeRecord, Integer> ROLLING_RECORDS = createField(DSL.name("rolling_records"), SQLDataType.INTEGER.nullable(false).defaultValue(DSL.inline("0", SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>stroom.shapeshifter_shape.lease_node</code>.
     */
    public final TableField<ShapeshifterShapeRecord, String> LEASE_NODE = createField(DSL.name("lease_node"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>stroom.shapeshifter_shape.lease_expiry_ms</code>.
     */
    public final TableField<ShapeshifterShapeRecord, Long> LEASE_EXPIRY_MS = createField(DSL.name("lease_expiry_ms"), SQLDataType.BIGINT, this, "");

    private ShapeshifterShape(Name alias, Table<ShapeshifterShapeRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private ShapeshifterShape(Name alias, Table<ShapeshifterShapeRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>stroom.shapeshifter_shape</code> table reference
     */
    public ShapeshifterShape(String alias) {
        this(DSL.name(alias), SHAPESHIFTER_SHAPE);
    }

    /**
     * Create an aliased <code>stroom.shapeshifter_shape</code> table reference
     */
    public ShapeshifterShape(Name alias) {
        this(alias, SHAPESHIFTER_SHAPE);
    }

    /**
     * Create a <code>stroom.shapeshifter_shape</code> table reference
     */
    public ShapeshifterShape() {
        this(DSL.name("shapeshifter_shape"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Stroom.STROOM;
    }

    @Override
    public Identity<ShapeshifterShapeRecord, Long> getIdentity() {
        return (Identity<ShapeshifterShapeRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<ShapeshifterShapeRecord> getPrimaryKey() {
        return Keys.KEY_SHAPESHIFTER_SHAPE_PRIMARY;
    }

    @Override
    public List<UniqueKey<ShapeshifterShapeRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.KEY_SHAPESHIFTER_SHAPE_SHAPESHIFTER_SHAPE_DOC_UUID_SHAPE_HASH);
    }

    @Override
    public TableField<ShapeshifterShapeRecord, Integer> getRecordVersion() {
        return VERSION;
    }

    @Override
    public ShapeshifterShape as(String alias) {
        return new ShapeshifterShape(DSL.name(alias), this);
    }

    @Override
    public ShapeshifterShape as(Name alias) {
        return new ShapeshifterShape(alias, this);
    }

    @Override
    public ShapeshifterShape as(Table<?> alias) {
        return new ShapeshifterShape(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public ShapeshifterShape rename(String name) {
        return new ShapeshifterShape(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public ShapeshifterShape rename(Name name) {
        return new ShapeshifterShape(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public ShapeshifterShape rename(Table<?> name) {
        return new ShapeshifterShape(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ShapeshifterShape where(Condition condition) {
        return new ShapeshifterShape(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ShapeshifterShape where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ShapeshifterShape where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ShapeshifterShape where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ShapeshifterShape where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ShapeshifterShape where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ShapeshifterShape where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ShapeshifterShape where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ShapeshifterShape whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ShapeshifterShape whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
