/*
 * This file is generated by jOOQ.
 */
package stroom.shapeshifter.ai.impl.db.jooq.tables;


import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import stroom.shapeshifter.ai.impl.db.jooq.Indexes;
import stroom.shapeshifter.ai.impl.db.jooq.Keys;
import stroom.shapeshifter.ai.impl.db.jooq.Stroom;
import stroom.shapeshifter.ai.impl.db.jooq.tables.records.ShapeshifterLedgerRecord;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ShapeshifterLedger extends TableImpl<ShapeshifterLedgerRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>stroom.shapeshifter_ledger</code>
     */
    public static final ShapeshifterLedger SHAPESHIFTER_LEDGER = new ShapeshifterLedger();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ShapeshifterLedgerRecord> getRecordType() {
        return ShapeshifterLedgerRecord.class;
    }

    /**
     * The column <code>stroom.shapeshifter_ledger.id</code>.
     */
    public final TableField<ShapeshifterLedgerRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>stroom.shapeshifter_ledger.create_time_ms</code>.
     */
    public final TableField<ShapeshifterLedgerRecord, Long> CREATE_TIME_MS = createField(DSL.name("create_time_ms"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>stroom.shapeshifter_ledger.doc_uuid</code>.
     */
    public final TableField<ShapeshifterLedgerRecord, String> DOC_UUID = createField(DSL.name("doc_uuid"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>stroom.shapeshifter_ledger.shape_id</code>.
     */
    public final TableField<ShapeshifterLedgerRecord, String> SHAPE_ID = createField(DSL.name("shape_id"), SQLDataType.VARCHAR(500).nullable(false), this, "");

    /**
     * The column <code>stroom.shapeshifter_ledger.input_meta_id</code>.
     */
    public final TableField<ShapeshifterLedgerRecord, Long> INPUT_META_ID = createField(DSL.name("input_meta_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>stroom.shapeshifter_ledger.reason</code>.
     */
    public final TableField<ShapeshifterLedgerRecord, String> REASON = createField(DSL.name("reason"), SQLDataType.CLOB.nullable(false), this, "");

    private ShapeshifterLedger(Name alias, Table<ShapeshifterLedgerRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private ShapeshifterLedger(Name alias, Table<ShapeshifterLedgerRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>stroom.shapeshifter_ledger</code> table reference
     */
    public ShapeshifterLedger(String alias) {
        this(DSL.name(alias), SHAPESHIFTER_LEDGER);
    }

    /**
     * Create an aliased <code>stroom.shapeshifter_ledger</code> table reference
     */
    public ShapeshifterLedger(Name alias) {
        this(alias, SHAPESHIFTER_LEDGER);
    }

    /**
     * Create a <code>stroom.shapeshifter_ledger</code> table reference
     */
    public ShapeshifterLedger() {
        this(DSL.name("shapeshifter_ledger"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Stroom.STROOM;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.SHAPESHIFTER_LEDGER_SHAPESHIFTER_LEDGER_DOC_UUID_SHAPE_ID, Indexes.SHAPESHIFTER_LEDGER_SHAPESHIFTER_LEDGER_INPUT_META_ID);
    }

    @Override
    public Identity<ShapeshifterLedgerRecord, Long> getIdentity() {
        return (Identity<ShapeshifterLedgerRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<ShapeshifterLedgerRecord> getPrimaryKey() {
        return Keys.KEY_SHAPESHIFTER_LEDGER_PRIMARY;
    }

    @Override
    public ShapeshifterLedger as(String alias) {
        return new ShapeshifterLedger(DSL.name(alias), this);
    }

    @Override
    public ShapeshifterLedger as(Name alias) {
        return new ShapeshifterLedger(alias, this);
    }

    @Override
    public ShapeshifterLedger as(Table<?> alias) {
        return new ShapeshifterLedger(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public ShapeshifterLedger rename(String name) {
        return new ShapeshifterLedger(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public ShapeshifterLedger rename(Name name) {
        return new ShapeshifterLedger(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public ShapeshifterLedger rename(Table<?> name) {
        return new ShapeshifterLedger(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ShapeshifterLedger where(Condition condition) {
        return new ShapeshifterLedger(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ShapeshifterLedger where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ShapeshifterLedger where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ShapeshifterLedger where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ShapeshifterLedger where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ShapeshifterLedger where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ShapeshifterLedger where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ShapeshifterLedger where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ShapeshifterLedger whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ShapeshifterLedger whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
