/*
 * This file is generated by jOOQ.
 */
package stroom.shapeshifter.ai.impl.db.jooq.tables;


import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import stroom.shapeshifter.ai.impl.db.jooq.Keys;
import stroom.shapeshifter.ai.impl.db.jooq.Stroom;
import stroom.shapeshifter.ai.impl.db.jooq.tables.records.ShapeshifterSpendRecord;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ShapeshifterSpend extends TableImpl<ShapeshifterSpendRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>stroom.shapeshifter_spend</code>
     */
    public static final ShapeshifterSpend SHAPESHIFTER_SPEND = new ShapeshifterSpend();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ShapeshifterSpendRecord> getRecordType() {
        return ShapeshifterSpendRecord.class;
    }

    /**
     * The column <code>stroom.shapeshifter_spend.id</code>.
     */
    public final TableField<ShapeshifterSpendRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>stroom.shapeshifter_spend.version</code>.
     */
    public final TableField<ShapeshifterSpendRecord, Integer> VERSION = createField(DSL.name("version"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>stroom.shapeshifter_spend.update_time_ms</code>.
     */
    public final TableField<ShapeshifterSpendRecord, Long> UPDATE_TIME_MS = createField(DSL.name("update_time_ms"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>stroom.shapeshifter_spend.doc_uuid</code>.
     */
    public final TableField<ShapeshifterSpendRecord, String> DOC_UUID = createField(DSL.name("doc_uuid"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>stroom.shapeshifter_spend.window_start_ms</code>.
     */
    public final TableField<ShapeshifterSpendRecord, Long> WINDOW_START_MS = createField(DSL.name("window_start_ms"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>stroom.shapeshifter_spend.tokens_spent</code>.
     */
    public final TableField<ShapeshifterSpendRecord, Long> TOKENS_SPENT = createField(DSL.name("tokens_spent"), SQLDataType.BIGINT.nullable(false).defaultValue(DSL.inline("0", SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>stroom.shapeshifter_spend.calls_made</code>.
     */
    public final TableField<ShapeshifterSpendRecord, Integer> CALLS_MADE = createField(DSL.name("calls_made"), SQLDataType.INTEGER.nullable(false).defaultValue(DSL.inline("0", SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>stroom.shapeshifter_spend.breaker_open_since_ms</code>.
     */
    public final TableField<ShapeshifterSpendRecord, Long> BREAKER_OPEN_SINCE_MS = createField(DSL.name("breaker_open_since_ms"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>stroom.shapeshifter_spend.breaker_reason</code>.
     */
    public final TableField<ShapeshifterSpendRecord, String> BREAKER_REASON = createField(DSL.name("breaker_reason"), SQLDataType.CLOB, this, "");

    private ShapeshifterSpend(Name alias, Table<ShapeshifterSpendRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private ShapeshifterSpend(Name alias, Table<ShapeshifterSpendRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>stroom.shapeshifter_spend</code> table reference
     */
    public ShapeshifterSpend(String alias) {
        this(DSL.name(alias), SHAPESHIFTER_SPEND);
    }

    /**
     * Create an aliased <code>stroom.shapeshifter_spend</code> table reference
     */
    public ShapeshifterSpend(Name alias) {
        this(alias, SHAPESHIFTER_SPEND);
    }

    /**
     * Create a <code>stroom.shapeshifter_spend</code> table reference
     */
    public ShapeshifterSpend() {
        this(DSL.name("shapeshifter_spend"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Stroom.STROOM;
    }

    @Override
    public Identity<ShapeshifterSpendRecord, Long> getIdentity() {
        return (Identity<ShapeshifterSpendRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<ShapeshifterSpendRecord> getPrimaryKey() {
        return Keys.KEY_SHAPESHIFTER_SPEND_PRIMARY;
    }

    @Override
    public List<UniqueKey<ShapeshifterSpendRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.KEY_SHAPESHIFTER_SPEND_SHAPESHIFTER_SPEND_DOC_UUID);
    }

    @Override
    public TableField<ShapeshifterSpendRecord, Integer> getRecordVersion() {
        return VERSION;
    }

    @Override
    public ShapeshifterSpend as(String alias) {
        return new ShapeshifterSpend(DSL.name(alias), this);
    }

    @Override
    public ShapeshifterSpend as(Name alias) {
        return new ShapeshifterSpend(alias, this);
    }

    @Override
    public ShapeshifterSpend as(Table<?> alias) {
        return new ShapeshifterSpend(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public ShapeshifterSpend rename(String name) {
        return new ShapeshifterSpend(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public ShapeshifterSpend rename(Name name) {
        return new ShapeshifterSpend(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public ShapeshifterSpend rename(Table<?> name) {
        return new ShapeshifterSpend(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ShapeshifterSpend where(Condition condition) {
        return new ShapeshifterSpend(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ShapeshifterSpend where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ShapeshifterSpend where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ShapeshifterSpend where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ShapeshifterSpend where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ShapeshifterSpend where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ShapeshifterSpend where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ShapeshifterSpend where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ShapeshifterSpend whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ShapeshifterSpend whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
