/*
 * This file is generated by jOOQ.
 */
package stroom.shapeshifter.ai.impl.db.jooq.tables;


import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import stroom.shapeshifter.ai.impl.db.jooq.Indexes;
import stroom.shapeshifter.ai.impl.db.jooq.Keys;
import stroom.shapeshifter.ai.impl.db.jooq.Stroom;
import stroom.shapeshifter.ai.impl.db.jooq.tables.records.ShapeshifterRuleRecord;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ShapeshifterRule extends TableImpl<ShapeshifterRuleRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>stroom.shapeshifter_rule</code>
     */
    public static final ShapeshifterRule SHAPESHIFTER_RULE = new ShapeshifterRule();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ShapeshifterRuleRecord> getRecordType() {
        return ShapeshifterRuleRecord.class;
    }

    /**
     * The column <code>stroom.shapeshifter_rule.id</code>.
     */
    public final TableField<ShapeshifterRuleRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>stroom.shapeshifter_rule.version</code>.
     */
    public final TableField<ShapeshifterRuleRecord, Integer> VERSION = createField(DSL.name("version"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>stroom.shapeshifter_rule.create_time_ms</code>.
     */
    public final TableField<ShapeshifterRuleRecord, Long> CREATE_TIME_MS = createField(DSL.name("create_time_ms"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>stroom.shapeshifter_rule.update_time_ms</code>.
     */
    public final TableField<ShapeshifterRuleRecord, Long> UPDATE_TIME_MS = createField(DSL.name("update_time_ms"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>stroom.shapeshifter_rule.doc_uuid</code>.
     */
    public final TableField<ShapeshifterRuleRecord, String> DOC_UUID = createField(DSL.name("doc_uuid"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>stroom.shapeshifter_rule.rule_uuid</code>.
     */
    public final TableField<ShapeshifterRuleRecord, String> RULE_UUID = createField(DSL.name("rule_uuid"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>stroom.shapeshifter_rule.sort_order</code>.
     */
    public final TableField<ShapeshifterRuleRecord, Integer> SORT_ORDER = createField(DSL.name("sort_order"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>stroom.shapeshifter_rule.expression</code>.
     */
    public final TableField<ShapeshifterRuleRecord, String> EXPRESSION = createField(DSL.name("expression"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>stroom.shapeshifter_rule.pipeline_type</code>.
     */
    public final TableField<ShapeshifterRuleRecord, String> PIPELINE_TYPE = createField(DSL.name("pipeline_type"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>stroom.shapeshifter_rule.pipeline_uuid</code>.
     */
    public final TableField<ShapeshifterRuleRecord, String> PIPELINE_UUID = createField(DSL.name("pipeline_uuid"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>stroom.shapeshifter_rule.pipeline_name</code>.
     */
    public final TableField<ShapeshifterRuleRecord, String> PIPELINE_NAME = createField(DSL.name("pipeline_name"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>stroom.shapeshifter_rule.pinned</code>.
     */
    public final TableField<ShapeshifterRuleRecord, Boolean> PINNED = createField(DSL.name("pinned"), SQLDataType.BOOLEAN.nullable(false).defaultValue(DSL.inline("0", SQLDataType.BOOLEAN)), this, "");

    /**
     * The column <code>stroom.shapeshifter_rule.draft</code>.
     */
    public final TableField<ShapeshifterRuleRecord, Boolean> DRAFT = createField(DSL.name("draft"), SQLDataType.BOOLEAN.nullable(false).defaultValue(DSL.inline("0", SQLDataType.BOOLEAN)), this, "");

    /**
     * The column <code>stroom.shapeshifter_rule.provisional</code>.
     */
    public final TableField<ShapeshifterRuleRecord, Boolean> PROVISIONAL = createField(DSL.name("provisional"), SQLDataType.BOOLEAN.nullable(false).defaultValue(DSL.inline("0", SQLDataType.BOOLEAN)), this, "");

    /**
     * The column <code>stroom.shapeshifter_rule.promoted_time_ms</code>.
     */
    public final TableField<ShapeshifterRuleRecord, Long> PROMOTED_TIME_MS = createField(DSL.name("promoted_time_ms"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>stroom.shapeshifter_rule.score</code>.
     */
    public final TableField<ShapeshifterRuleRecord, Double> SCORE = createField(DSL.name("score"), SQLDataType.DOUBLE, this, "");

    /**
     * The column <code>stroom.shapeshifter_rule.boundary_element</code>.
     */
    public final TableField<ShapeshifterRuleRecord, String> BOUNDARY_ELEMENT = createField(DSL.name("boundary_element"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>stroom.shapeshifter_rule.boundary_array</code>.
     */
    public final TableField<ShapeshifterRuleRecord, String> BOUNDARY_ARRAY = createField(DSL.name("boundary_array"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>stroom.shapeshifter_rule.boundary_depth</code>.
     */
    public final TableField<ShapeshifterRuleRecord, Integer> BOUNDARY_DEPTH = createField(DSL.name("boundary_depth"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>stroom.shapeshifter_rule.shape_id</code>.
     */
    public final TableField<ShapeshifterRuleRecord, String> SHAPE_ID = createField(DSL.name("shape_id"), SQLDataType.CLOB, this, "");

    private ShapeshifterRule(Name alias, Table<ShapeshifterRuleRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private ShapeshifterRule(Name alias, Table<ShapeshifterRuleRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>stroom.shapeshifter_rule</code> table reference
     */
    public ShapeshifterRule(String alias) {
        this(DSL.name(alias), SHAPESHIFTER_RULE);
    }

    /**
     * Create an aliased <code>stroom.shapeshifter_rule</code> table reference
     */
    public ShapeshifterRule(Name alias) {
        this(alias, SHAPESHIFTER_RULE);
    }

    /**
     * Create a <code>stroom.shapeshifter_rule</code> table reference
     */
    public ShapeshifterRule() {
        this(DSL.name("shapeshifter_rule"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Stroom.STROOM;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.SHAPESHIFTER_RULE_SHAPESHIFTER_RULE_DOC_UUID_SORT_ORDER);
    }

    @Override
    public Identity<ShapeshifterRuleRecord, Long> getIdentity() {
        return (Identity<ShapeshifterRuleRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<ShapeshifterRuleRecord> getPrimaryKey() {
        return Keys.KEY_SHAPESHIFTER_RULE_PRIMARY;
    }

    @Override
    public List<UniqueKey<ShapeshifterRuleRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.KEY_SHAPESHIFTER_RULE_SHAPESHIFTER_RULE_DOC_UUID_RULE_UUID);
    }

    @Override
    public TableField<ShapeshifterRuleRecord, Integer> getRecordVersion() {
        return VERSION;
    }

    @Override
    public ShapeshifterRule as(String alias) {
        return new ShapeshifterRule(DSL.name(alias), this);
    }

    @Override
    public ShapeshifterRule as(Name alias) {
        return new ShapeshifterRule(alias, this);
    }

    @Override
    public ShapeshifterRule as(Table<?> alias) {
        return new ShapeshifterRule(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public ShapeshifterRule rename(String name) {
        return new ShapeshifterRule(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public ShapeshifterRule rename(Name name) {
        return new ShapeshifterRule(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public ShapeshifterRule rename(Table<?> name) {
        return new ShapeshifterRule(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ShapeshifterRule where(Condition condition) {
        return new ShapeshifterRule(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ShapeshifterRule where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ShapeshifterRule where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ShapeshifterRule where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ShapeshifterRule where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ShapeshifterRule where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ShapeshifterRule where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ShapeshifterRule where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ShapeshifterRule whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ShapeshifterRule whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
