/*
 * This file is generated by jOOQ.
 */
package stroom.shapeshifter.ai.impl.db.jooq.tables;


import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import stroom.shapeshifter.ai.impl.db.jooq.Indexes;
import stroom.shapeshifter.ai.impl.db.jooq.Keys;
import stroom.shapeshifter.ai.impl.db.jooq.Stroom;
import stroom.shapeshifter.ai.impl.db.jooq.tables.records.ShapeshifterGuidanceRecord;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ShapeshifterGuidance extends TableImpl<ShapeshifterGuidanceRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>stroom.shapeshifter_guidance</code>
     */
    public static final ShapeshifterGuidance SHAPESHIFTER_GUIDANCE = new ShapeshifterGuidance();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ShapeshifterGuidanceRecord> getRecordType() {
        return ShapeshifterGuidanceRecord.class;
    }

    /**
     * The column <code>stroom.shapeshifter_guidance.id</code>.
     */
    public final TableField<ShapeshifterGuidanceRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>stroom.shapeshifter_guidance.create_time_ms</code>.
     */
    public final TableField<ShapeshifterGuidanceRecord, Long> CREATE_TIME_MS = createField(DSL.name("create_time_ms"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>stroom.shapeshifter_guidance.doc_uuid</code>.
     */
    public final TableField<ShapeshifterGuidanceRecord, String> DOC_UUID = createField(DSL.name("doc_uuid"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>stroom.shapeshifter_guidance.shape_hash</code>.
     */
    public final TableField<ShapeshifterGuidanceRecord, String> SHAPE_HASH = createField(DSL.name("shape_hash"), SQLDataType.VARCHAR(64).nullable(false), this, "");

    /**
     * The column <code>stroom.shapeshifter_guidance.shape_id</code>.
     */
    public final TableField<ShapeshifterGuidanceRecord, String> SHAPE_ID = createField(DSL.name("shape_id"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>stroom.shapeshifter_guidance.message</code>.
     */
    public final TableField<ShapeshifterGuidanceRecord, String> MESSAGE = createField(DSL.name("message"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>stroom.shapeshifter_guidance.author</code>.
     */
    public final TableField<ShapeshifterGuidanceRecord, String> AUTHOR = createField(DSL.name("author"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    private ShapeshifterGuidance(Name alias, Table<ShapeshifterGuidanceRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private ShapeshifterGuidance(Name alias, Table<ShapeshifterGuidanceRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>stroom.shapeshifter_guidance</code> table
     * reference
     */
    public ShapeshifterGuidance(String alias) {
        this(DSL.name(alias), SHAPESHIFTER_GUIDANCE);
    }

    /**
     * Create an aliased <code>stroom.shapeshifter_guidance</code> table
     * reference
     */
    public ShapeshifterGuidance(Name alias) {
        this(alias, SHAPESHIFTER_GUIDANCE);
    }

    /**
     * Create a <code>stroom.shapeshifter_guidance</code> table reference
     */
    public ShapeshifterGuidance() {
        this(DSL.name("shapeshifter_guidance"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Stroom.STROOM;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.SHAPESHIFTER_GUIDANCE_SHAPESHIFTER_GUIDANCE_DOC_SHAPE);
    }

    @Override
    public Identity<ShapeshifterGuidanceRecord, Long> getIdentity() {
        return (Identity<ShapeshifterGuidanceRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<ShapeshifterGuidanceRecord> getPrimaryKey() {
        return Keys.KEY_SHAPESHIFTER_GUIDANCE_PRIMARY;
    }

    @Override
    public ShapeshifterGuidance as(String alias) {
        return new ShapeshifterGuidance(DSL.name(alias), this);
    }

    @Override
    public ShapeshifterGuidance as(Name alias) {
        return new ShapeshifterGuidance(alias, this);
    }

    @Override
    public ShapeshifterGuidance as(Table<?> alias) {
        return new ShapeshifterGuidance(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public ShapeshifterGuidance rename(String name) {
        return new ShapeshifterGuidance(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public ShapeshifterGuidance rename(Name name) {
        return new ShapeshifterGuidance(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public ShapeshifterGuidance rename(Table<?> name) {
        return new ShapeshifterGuidance(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ShapeshifterGuidance where(Condition condition) {
        return new ShapeshifterGuidance(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ShapeshifterGuidance where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ShapeshifterGuidance where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ShapeshifterGuidance where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ShapeshifterGuidance where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ShapeshifterGuidance where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ShapeshifterGuidance where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ShapeshifterGuidance where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ShapeshifterGuidance whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ShapeshifterGuidance whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
