/*
 * This file is generated by jOOQ.
 */
package stroom.shapeshifter.ai.impl.db.jooq.tables.records;


import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;

import stroom.shapeshifter.ai.impl.db.jooq.tables.ShapeshifterRule;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ShapeshifterRuleRecord extends UpdatableRecordImpl<ShapeshifterRuleRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>stroom.shapeshifter_rule.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>stroom.shapeshifter_rule.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>stroom.shapeshifter_rule.version</code>.
     */
    public void setVersion(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>stroom.shapeshifter_rule.version</code>.
     */
    public Integer getVersion() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>stroom.shapeshifter_rule.create_time_ms</code>.
     */
    public void setCreateTimeMs(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>stroom.shapeshifter_rule.create_time_ms</code>.
     */
    public Long getCreateTimeMs() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>stroom.shapeshifter_rule.update_time_ms</code>.
     */
    public void setUpdateTimeMs(Long value) {
        set(3, value);
    }

    /**
     * Getter for <code>stroom.shapeshifter_rule.update_time_ms</code>.
     */
    public Long getUpdateTimeMs() {
        return (Long) get(3);
    }

    /**
     * Setter for <code>stroom.shapeshifter_rule.doc_uuid</code>.
     */
    public void setDocUuid(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>stroom.shapeshifter_rule.doc_uuid</code>.
     */
    public String getDocUuid() {
        return (String) get(4);
    }

    /**
     * Setter for <code>stroom.shapeshifter_rule.rule_uuid</code>.
     */
    public void setRuleUuid(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>stroom.shapeshifter_rule.rule_uuid</code>.
     */
    public String getRuleUuid() {
        return (String) get(5);
    }

    /**
     * Setter for <code>stroom.shapeshifter_rule.sort_order</code>.
     */
    public void setSortOrder(Integer value) {
        set(6, value);
    }

    /**
     * Getter for <code>stroom.shapeshifter_rule.sort_order</code>.
     */
    public Integer getSortOrder() {
        return (Integer) get(6);
    }

    /**
     * Setter for <code>stroom.shapeshifter_rule.expression</code>.
     */
    public void setExpression(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>stroom.shapeshifter_rule.expression</code>.
     */
    public String getExpression() {
        return (String) get(7);
    }

    /**
     * Setter for <code>stroom.shapeshifter_rule.pipeline_type</code>.
     */
    public void setPipelineType(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>stroom.shapeshifter_rule.pipeline_type</code>.
     */
    public String getPipelineType() {
        return (String) get(8);
    }

    /**
     * Setter for <code>stroom.shapeshifter_rule.pipeline_uuid</code>.
     */
    public void setPipelineUuid(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>stroom.shapeshifter_rule.pipeline_uuid</code>.
     */
    public String getPipelineUuid() {
        return (String) get(9);
    }

    /**
     * Setter for <code>stroom.shapeshifter_rule.pipeline_name</code>.
     */
    public void setPipelineName(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>stroom.shapeshifter_rule.pipeline_name</code>.
     */
    public String getPipelineName() {
        return (String) get(10);
    }

    /**
     * Setter for <code>stroom.shapeshifter_rule.pinned</code>.
     */
    public void setPinned(Boolean value) {
        set(11, value);
    }

    /**
     * Getter for <code>stroom.shapeshifter_rule.pinned</code>.
     */
    public Boolean getPinned() {
        return (Boolean) get(11);
    }

    /**
     * Setter for <code>stroom.shapeshifter_rule.draft</code>.
     */
    public void setDraft(Boolean value) {
        set(12, value);
    }

    /**
     * Getter for <code>stroom.shapeshifter_rule.draft</code>.
     */
    public Boolean getDraft() {
        return (Boolean) get(12);
    }

    /**
     * Setter for <code>stroom.shapeshifter_rule.provisional</code>.
     */
    public void setProvisional(Boolean value) {
        set(13, value);
    }

    /**
     * Getter for <code>stroom.shapeshifter_rule.provisional</code>.
     */
    public Boolean getProvisional() {
        return (Boolean) get(13);
    }

    /**
     * Setter for <code>stroom.shapeshifter_rule.promoted_time_ms</code>.
     */
    public void setPromotedTimeMs(Long value) {
        set(14, value);
    }

    /**
     * Getter for <code>stroom.shapeshifter_rule.promoted_time_ms</code>.
     */
    public Long getPromotedTimeMs() {
        return (Long) get(14);
    }

    /**
     * Setter for <code>stroom.shapeshifter_rule.score</code>.
     */
    public void setScore(Double value) {
        set(15, value);
    }

    /**
     * Getter for <code>stroom.shapeshifter_rule.score</code>.
     */
    public Double getScore() {
        return (Double) get(15);
    }

    /**
     * Setter for <code>stroom.shapeshifter_rule.boundary_element</code>.
     */
    public void setBoundaryElement(String value) {
        set(16, value);
    }

    /**
     * Getter for <code>stroom.shapeshifter_rule.boundary_element</code>.
     */
    public String getBoundaryElement() {
        return (String) get(16);
    }

    /**
     * Setter for <code>stroom.shapeshifter_rule.boundary_array</code>.
     */
    public void setBoundaryArray(String value) {
        set(17, value);
    }

    /**
     * Getter for <code>stroom.shapeshifter_rule.boundary_array</code>.
     */
    public String getBoundaryArray() {
        return (String) get(17);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ShapeshifterRuleRecord
     */
    public ShapeshifterRuleRecord() {
        super(ShapeshifterRule.SHAPESHIFTER_RULE);
    }

    /**
     * Create a detached, initialised ShapeshifterRuleRecord
     */
    public ShapeshifterRuleRecord(Long id, Integer version, Long createTimeMs, Long updateTimeMs, String docUuid, String ruleUuid, Integer sortOrder, String expression, String pipelineType, String pipelineUuid, String pipelineName, Boolean pinned, Boolean draft, Boolean provisional, Long promotedTimeMs, Double score, String boundaryElement, String boundaryArray) {
        super(ShapeshifterRule.SHAPESHIFTER_RULE);

        setId(id);
        setVersion(version);
        setCreateTimeMs(createTimeMs);
        setUpdateTimeMs(updateTimeMs);
        setDocUuid(docUuid);
        setRuleUuid(ruleUuid);
        setSortOrder(sortOrder);
        setExpression(expression);
        setPipelineType(pipelineType);
        setPipelineUuid(pipelineUuid);
        setPipelineName(pipelineName);
        setPinned(pinned);
        setDraft(draft);
        setProvisional(provisional);
        setPromotedTimeMs(promotedTimeMs);
        setScore(score);
        setBoundaryElement(boundaryElement);
        setBoundaryArray(boundaryArray);
        resetTouchedOnNotNull();
    }
}
