/*
 * This file is generated by jOOQ.
 */
package stroom.shapeshifter.ai.impl.db.jooq.tables.records;


import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;

import stroom.shapeshifter.ai.impl.db.jooq.tables.ShapeshifterGuidance;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ShapeshifterGuidanceRecord extends UpdatableRecordImpl<ShapeshifterGuidanceRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>stroom.shapeshifter_guidance.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>stroom.shapeshifter_guidance.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>stroom.shapeshifter_guidance.create_time_ms</code>.
     */
    public void setCreateTimeMs(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>stroom.shapeshifter_guidance.create_time_ms</code>.
     */
    public Long getCreateTimeMs() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>stroom.shapeshifter_guidance.doc_uuid</code>.
     */
    public void setDocUuid(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>stroom.shapeshifter_guidance.doc_uuid</code>.
     */
    public String getDocUuid() {
        return (String) get(2);
    }

    /**
     * Setter for <code>stroom.shapeshifter_guidance.shape_hash</code>.
     */
    public void setShapeHash(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>stroom.shapeshifter_guidance.shape_hash</code>.
     */
    public String getShapeHash() {
        return (String) get(3);
    }

    /**
     * Setter for <code>stroom.shapeshifter_guidance.shape_id</code>.
     */
    public void setShapeId(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>stroom.shapeshifter_guidance.shape_id</code>.
     */
    public String getShapeId() {
        return (String) get(4);
    }

    /**
     * Setter for <code>stroom.shapeshifter_guidance.message</code>.
     */
    public void setMessage(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>stroom.shapeshifter_guidance.message</code>.
     */
    public String getMessage() {
        return (String) get(5);
    }

    /**
     * Setter for <code>stroom.shapeshifter_guidance.author</code>.
     */
    public void setAuthor(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>stroom.shapeshifter_guidance.author</code>.
     */
    public String getAuthor() {
        return (String) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ShapeshifterGuidanceRecord
     */
    public ShapeshifterGuidanceRecord() {
        super(ShapeshifterGuidance.SHAPESHIFTER_GUIDANCE);
    }

    /**
     * Create a detached, initialised ShapeshifterGuidanceRecord
     */
    public ShapeshifterGuidanceRecord(Long id, Long createTimeMs, String docUuid, String shapeHash, String shapeId, String message, String author) {
        super(ShapeshifterGuidance.SHAPESHIFTER_GUIDANCE);

        setId(id);
        setCreateTimeMs(createTimeMs);
        setDocUuid(docUuid);
        setShapeHash(shapeHash);
        setShapeId(shapeId);
        setMessage(message);
        setAuthor(author);
        resetTouchedOnNotNull();
    }
}
