/*
 * This file is generated by jOOQ.
 */
package stroom.shapeshifter.ai.impl.db.jooq.tables.records;


import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;

import stroom.shapeshifter.ai.impl.db.jooq.tables.ShapeshifterSpend;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ShapeshifterSpendRecord extends UpdatableRecordImpl<ShapeshifterSpendRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>stroom.shapeshifter_spend.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>stroom.shapeshifter_spend.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>stroom.shapeshifter_spend.version</code>.
     */
    public void setVersion(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>stroom.shapeshifter_spend.version</code>.
     */
    public Integer getVersion() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>stroom.shapeshifter_spend.update_time_ms</code>.
     */
    public void setUpdateTimeMs(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>stroom.shapeshifter_spend.update_time_ms</code>.
     */
    public Long getUpdateTimeMs() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>stroom.shapeshifter_spend.doc_uuid</code>.
     */
    public void setDocUuid(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>stroom.shapeshifter_spend.doc_uuid</code>.
     */
    public String getDocUuid() {
        return (String) get(3);
    }

    /**
     * Setter for <code>stroom.shapeshifter_spend.window_start_ms</code>.
     */
    public void setWindowStartMs(Long value) {
        set(4, value);
    }

    /**
     * Getter for <code>stroom.shapeshifter_spend.window_start_ms</code>.
     */
    public Long getWindowStartMs() {
        return (Long) get(4);
    }

    /**
     * Setter for <code>stroom.shapeshifter_spend.tokens_spent</code>.
     */
    public void setTokensSpent(Long value) {
        set(5, value);
    }

    /**
     * Getter for <code>stroom.shapeshifter_spend.tokens_spent</code>.
     */
    public Long getTokensSpent() {
        return (Long) get(5);
    }

    /**
     * Setter for <code>stroom.shapeshifter_spend.calls_made</code>.
     */
    public void setCallsMade(Integer value) {
        set(6, value);
    }

    /**
     * Getter for <code>stroom.shapeshifter_spend.calls_made</code>.
     */
    public Integer getCallsMade() {
        return (Integer) get(6);
    }

    /**
     * Setter for <code>stroom.shapeshifter_spend.breaker_open_since_ms</code>.
     */
    public void setBreakerOpenSinceMs(Long value) {
        set(7, value);
    }

    /**
     * Getter for <code>stroom.shapeshifter_spend.breaker_open_since_ms</code>.
     */
    public Long getBreakerOpenSinceMs() {
        return (Long) get(7);
    }

    /**
     * Setter for <code>stroom.shapeshifter_spend.breaker_reason</code>.
     */
    public void setBreakerReason(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>stroom.shapeshifter_spend.breaker_reason</code>.
     */
    public String getBreakerReason() {
        return (String) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ShapeshifterSpendRecord
     */
    public ShapeshifterSpendRecord() {
        super(ShapeshifterSpend.SHAPESHIFTER_SPEND);
    }

    /**
     * Create a detached, initialised ShapeshifterSpendRecord
     */
    public ShapeshifterSpendRecord(Long id, Integer version, Long updateTimeMs, String docUuid, Long windowStartMs, Long tokensSpent, Integer callsMade, Long breakerOpenSinceMs, String breakerReason) {
        super(ShapeshifterSpend.SHAPESHIFTER_SPEND);

        setId(id);
        setVersion(version);
        setUpdateTimeMs(updateTimeMs);
        setDocUuid(docUuid);
        setWindowStartMs(windowStartMs);
        setTokensSpent(tokensSpent);
        setCallsMade(callsMade);
        setBreakerOpenSinceMs(breakerOpenSinceMs);
        setBreakerReason(breakerReason);
        resetTouchedOnNotNull();
    }
}
