/*
 * This file is generated by jOOQ.
 */
package stroom.shapeshifter.ai.impl.db.jooq.tables.records;


import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;

import stroom.shapeshifter.ai.impl.db.jooq.tables.ShapeshifterAttempt;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ShapeshifterAttemptRecord extends UpdatableRecordImpl<ShapeshifterAttemptRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>stroom.shapeshifter_attempt.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>stroom.shapeshifter_attempt.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>stroom.shapeshifter_attempt.version</code>.
     */
    public void setVersion(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>stroom.shapeshifter_attempt.version</code>.
     */
    public Integer getVersion() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>stroom.shapeshifter_attempt.create_time_ms</code>.
     */
    public void setCreateTimeMs(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>stroom.shapeshifter_attempt.create_time_ms</code>.
     */
    public Long getCreateTimeMs() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>stroom.shapeshifter_attempt.update_time_ms</code>.
     */
    public void setUpdateTimeMs(Long value) {
        set(3, value);
    }

    /**
     * Getter for <code>stroom.shapeshifter_attempt.update_time_ms</code>.
     */
    public Long getUpdateTimeMs() {
        return (Long) get(3);
    }

    /**
     * Setter for <code>stroom.shapeshifter_attempt.doc_uuid</code>.
     */
    public void setDocUuid(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>stroom.shapeshifter_attempt.doc_uuid</code>.
     */
    public String getDocUuid() {
        return (String) get(4);
    }

    /**
     * Setter for <code>stroom.shapeshifter_attempt.shape_hash</code>.
     */
    public void setShapeHash(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>stroom.shapeshifter_attempt.shape_hash</code>.
     */
    public String getShapeHash() {
        return (String) get(5);
    }

    /**
     * Setter for <code>stroom.shapeshifter_attempt.shape_id</code>.
     */
    public void setShapeId(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>stroom.shapeshifter_attempt.shape_id</code>.
     */
    public String getShapeId() {
        return (String) get(6);
    }

    /**
     * Setter for <code>stroom.shapeshifter_attempt.feed_name</code>.
     */
    public void setFeedName(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>stroom.shapeshifter_attempt.feed_name</code>.
     */
    public String getFeedName() {
        return (String) get(7);
    }

    /**
     * Setter for <code>stroom.shapeshifter_attempt.type_name</code>.
     */
    public void setTypeName(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>stroom.shapeshifter_attempt.type_name</code>.
     */
    public String getTypeName() {
        return (String) get(8);
    }

    /**
     * Setter for <code>stroom.shapeshifter_attempt.input_meta_id</code>.
     */
    public void setInputMetaId(Long value) {
        set(9, value);
    }

    /**
     * Getter for <code>stroom.shapeshifter_attempt.input_meta_id</code>.
     */
    public Long getInputMetaId() {
        return (Long) get(9);
    }

    /**
     * Setter for <code>stroom.shapeshifter_attempt.node_name</code>.
     */
    public void setNodeName(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>stroom.shapeshifter_attempt.node_name</code>.
     */
    public String getNodeName() {
        return (String) get(10);
    }

    /**
     * Setter for <code>stroom.shapeshifter_attempt.execution_mode</code>.
     */
    public void setExecutionMode(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>stroom.shapeshifter_attempt.execution_mode</code>.
     */
    public String getExecutionMode() {
        return (String) get(11);
    }

    /**
     * Setter for <code>stroom.shapeshifter_attempt.promotion_mode</code>.
     */
    public void setPromotionMode(String value) {
        set(12, value);
    }

    /**
     * Getter for <code>stroom.shapeshifter_attempt.promotion_mode</code>.
     */
    public String getPromotionMode() {
        return (String) get(12);
    }

    /**
     * Setter for <code>stroom.shapeshifter_attempt.status</code>.
     */
    public void setStatus(String value) {
        set(13, value);
    }

    /**
     * Getter for <code>stroom.shapeshifter_attempt.status</code>.
     */
    public String getStatus() {
        return (String) get(13);
    }

    /**
     * Setter for <code>stroom.shapeshifter_attempt.decision</code>.
     */
    public void setDecision(String value) {
        set(14, value);
    }

    /**
     * Getter for <code>stroom.shapeshifter_attempt.decision</code>.
     */
    public String getDecision() {
        return (String) get(14);
    }

    /**
     * Setter for <code>stroom.shapeshifter_attempt.rule_uuid</code>.
     */
    public void setRuleUuid(String value) {
        set(15, value);
    }

    /**
     * Getter for <code>stroom.shapeshifter_attempt.rule_uuid</code>.
     */
    public String getRuleUuid() {
        return (String) get(15);
    }

    /**
     * Setter for <code>stroom.shapeshifter_attempt.score</code>.
     */
    public void setScore(Double value) {
        set(16, value);
    }

    /**
     * Getter for <code>stroom.shapeshifter_attempt.score</code>.
     */
    public Double getScore() {
        return (Double) get(16);
    }

    /**
     * Setter for <code>stroom.shapeshifter_attempt.tokens_spent</code>.
     */
    public void setTokensSpent(Long value) {
        set(17, value);
    }

    /**
     * Getter for <code>stroom.shapeshifter_attempt.tokens_spent</code>.
     */
    public Long getTokensSpent() {
        return (Long) get(17);
    }

    /**
     * Setter for <code>stroom.shapeshifter_attempt.expiry_ms</code>.
     */
    public void setExpiryMs(Long value) {
        set(18, value);
    }

    /**
     * Getter for <code>stroom.shapeshifter_attempt.expiry_ms</code>.
     */
    public Long getExpiryMs() {
        return (Long) get(18);
    }

    /**
     * Setter for <code>stroom.shapeshifter_attempt.claim_key</code>.
     */
    public void setClaimKey(String value) {
        set(19, value);
    }

    /**
     * Getter for <code>stroom.shapeshifter_attempt.claim_key</code>.
     */
    public String getClaimKey() {
        return (String) get(19);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ShapeshifterAttemptRecord
     */
    public ShapeshifterAttemptRecord() {
        super(ShapeshifterAttempt.SHAPESHIFTER_ATTEMPT);
    }

    /**
     * Create a detached, initialised ShapeshifterAttemptRecord
     */
    public ShapeshifterAttemptRecord(Long id, Integer version, Long createTimeMs, Long updateTimeMs, String docUuid, String shapeHash, String shapeId, String feedName, String typeName, Long inputMetaId, String nodeName, String executionMode, String promotionMode, String status, String decision, String ruleUuid, Double score, Long tokensSpent, Long expiryMs, String claimKey) {
        super(ShapeshifterAttempt.SHAPESHIFTER_ATTEMPT);

        setId(id);
        setVersion(version);
        setCreateTimeMs(createTimeMs);
        setUpdateTimeMs(updateTimeMs);
        setDocUuid(docUuid);
        setShapeHash(shapeHash);
        setShapeId(shapeId);
        setFeedName(feedName);
        setTypeName(typeName);
        setInputMetaId(inputMetaId);
        setNodeName(nodeName);
        setExecutionMode(executionMode);
        setPromotionMode(promotionMode);
        setStatus(status);
        setDecision(decision);
        setRuleUuid(ruleUuid);
        setScore(score);
        setTokensSpent(tokensSpent);
        setExpiryMs(expiryMs);
        setClaimKey(claimKey);
        resetTouchedOnNotNull();
    }
}
