/*
 * This file is generated by jOOQ.
 */
package stroom.shapeshifter.ai.impl.db.jooq.tables.records;


import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;

import stroom.shapeshifter.ai.impl.db.jooq.tables.ShapeshifterLedger;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ShapeshifterLedgerRecord extends UpdatableRecordImpl<ShapeshifterLedgerRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>stroom.shapeshifter_ledger.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>stroom.shapeshifter_ledger.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>stroom.shapeshifter_ledger.create_time_ms</code>.
     */
    public void setCreateTimeMs(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>stroom.shapeshifter_ledger.create_time_ms</code>.
     */
    public Long getCreateTimeMs() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>stroom.shapeshifter_ledger.doc_uuid</code>.
     */
    public void setDocUuid(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>stroom.shapeshifter_ledger.doc_uuid</code>.
     */
    public String getDocUuid() {
        return (String) get(2);
    }

    /**
     * Setter for <code>stroom.shapeshifter_ledger.shape_hash</code>.
     */
    public void setShapeHash(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>stroom.shapeshifter_ledger.shape_hash</code>.
     */
    public String getShapeHash() {
        return (String) get(3);
    }

    /**
     * Setter for <code>stroom.shapeshifter_ledger.shape_id</code>.
     */
    public void setShapeId(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>stroom.shapeshifter_ledger.shape_id</code>.
     */
    public String getShapeId() {
        return (String) get(4);
    }

    /**
     * Setter for <code>stroom.shapeshifter_ledger.input_meta_id</code>.
     */
    public void setInputMetaId(Long value) {
        set(5, value);
    }

    /**
     * Getter for <code>stroom.shapeshifter_ledger.input_meta_id</code>.
     */
    public Long getInputMetaId() {
        return (Long) get(5);
    }

    /**
     * Setter for <code>stroom.shapeshifter_ledger.reason</code>.
     */
    public void setReason(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>stroom.shapeshifter_ledger.reason</code>.
     */
    public String getReason() {
        return (String) get(6);
    }

    /**
     * Setter for <code>stroom.shapeshifter_ledger.pipeline_uuid</code>.
     */
    public void setPipelineUuid(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>stroom.shapeshifter_ledger.pipeline_uuid</code>.
     */
    public String getPipelineUuid() {
        return (String) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ShapeshifterLedgerRecord
     */
    public ShapeshifterLedgerRecord() {
        super(ShapeshifterLedger.SHAPESHIFTER_LEDGER);
    }

    /**
     * Create a detached, initialised ShapeshifterLedgerRecord
     */
    public ShapeshifterLedgerRecord(Long id, Long createTimeMs, String docUuid, String shapeHash, String shapeId, Long inputMetaId, String reason, String pipelineUuid) {
        super(ShapeshifterLedger.SHAPESHIFTER_LEDGER);

        setId(id);
        setCreateTimeMs(createTimeMs);
        setDocUuid(docUuid);
        setShapeHash(shapeHash);
        setShapeId(shapeId);
        setInputMetaId(inputMetaId);
        setReason(reason);
        setPipelineUuid(pipelineUuid);
        resetTouchedOnNotNull();
    }
}
