/*
 * This file is generated by jOOQ.
 */
package stroom.shapeshifter.ai.impl.db.jooq.tables.records;


import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;

import stroom.shapeshifter.ai.impl.db.jooq.tables.ShapeshifterTurn;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ShapeshifterTurnRecord extends UpdatableRecordImpl<ShapeshifterTurnRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>stroom.shapeshifter_turn.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>stroom.shapeshifter_turn.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>stroom.shapeshifter_turn.create_time_ms</code>.
     */
    public void setCreateTimeMs(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>stroom.shapeshifter_turn.create_time_ms</code>.
     */
    public Long getCreateTimeMs() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>stroom.shapeshifter_turn.fk_attempt_id</code>.
     */
    public void setFkAttemptId(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>stroom.shapeshifter_turn.fk_attempt_id</code>.
     */
    public Long getFkAttemptId() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>stroom.shapeshifter_turn.turn_number</code>.
     */
    public void setTurnNumber(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>stroom.shapeshifter_turn.turn_number</code>.
     */
    public Integer getTurnNumber() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>stroom.shapeshifter_turn.step_id</code>.
     */
    public void setStepId(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>stroom.shapeshifter_turn.step_id</code>.
     */
    public String getStepId() {
        return (String) get(4);
    }

    /**
     * Setter for <code>stroom.shapeshifter_turn.candidate</code>.
     */
    public void setCandidate(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>stroom.shapeshifter_turn.candidate</code>.
     */
    public Integer getCandidate() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>stroom.shapeshifter_turn.question_kind</code>.
     */
    public void setQuestionKind(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>stroom.shapeshifter_turn.question_kind</code>.
     */
    public String getQuestionKind() {
        return (String) get(6);
    }

    /**
     * Setter for <code>stroom.shapeshifter_turn.question</code>.
     */
    public void setQuestion(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>stroom.shapeshifter_turn.question</code>.
     */
    public String getQuestion() {
        return (String) get(7);
    }

    /**
     * Setter for <code>stroom.shapeshifter_turn.answer</code>.
     */
    public void setAnswer(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>stroom.shapeshifter_turn.answer</code>.
     */
    public String getAnswer() {
        return (String) get(8);
    }

    /**
     * Setter for <code>stroom.shapeshifter_turn.answered_by</code>.
     */
    public void setAnsweredBy(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>stroom.shapeshifter_turn.answered_by</code>.
     */
    public String getAnsweredBy() {
        return (String) get(9);
    }

    /**
     * Setter for <code>stroom.shapeshifter_turn.outcome</code>.
     */
    public void setOutcome(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>stroom.shapeshifter_turn.outcome</code>.
     */
    public String getOutcome() {
        return (String) get(10);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ShapeshifterTurnRecord
     */
    public ShapeshifterTurnRecord() {
        super(ShapeshifterTurn.SHAPESHIFTER_TURN);
    }

    /**
     * Create a detached, initialised ShapeshifterTurnRecord
     */
    public ShapeshifterTurnRecord(Long id, Long createTimeMs, Long fkAttemptId, Integer turnNumber, String stepId, Integer candidate, String questionKind, String question, String answer, String answeredBy, String outcome) {
        super(ShapeshifterTurn.SHAPESHIFTER_TURN);

        setId(id);
        setCreateTimeMs(createTimeMs);
        setFkAttemptId(fkAttemptId);
        setTurnNumber(turnNumber);
        setStepId(stepId);
        setCandidate(candidate);
        setQuestionKind(questionKind);
        setQuestion(question);
        setAnswer(answer);
        setAnsweredBy(answeredBy);
        setOutcome(outcome);
        resetTouchedOnNotNull();
    }
}
