/*
 * This file is generated by jOOQ.
 */
package stroom.shapeshifter.ai.impl.db.jooq.tables.records;


import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;

import stroom.shapeshifter.ai.impl.db.jooq.tables.ShapeshifterFeedState;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ShapeshifterFeedStateRecord extends UpdatableRecordImpl<ShapeshifterFeedStateRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>stroom.shapeshifter_feed_state.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>stroom.shapeshifter_feed_state.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>stroom.shapeshifter_feed_state.version</code>.
     */
    public void setVersion(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>stroom.shapeshifter_feed_state.version</code>.
     */
    public Integer getVersion() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>stroom.shapeshifter_feed_state.update_time_ms</code>.
     */
    public void setUpdateTimeMs(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>stroom.shapeshifter_feed_state.update_time_ms</code>.
     */
    public Long getUpdateTimeMs() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>stroom.shapeshifter_feed_state.doc_uuid</code>.
     */
    public void setDocUuid(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>stroom.shapeshifter_feed_state.doc_uuid</code>.
     */
    public String getDocUuid() {
        return (String) get(3);
    }

    /**
     * Setter for <code>stroom.shapeshifter_feed_state.feed_name</code>.
     */
    public void setFeedName(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>stroom.shapeshifter_feed_state.feed_name</code>.
     */
    public String getFeedName() {
        return (String) get(4);
    }

    /**
     * Setter for <code>stroom.shapeshifter_feed_state.failure_streak</code>.
     */
    public void setFailureStreak(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>stroom.shapeshifter_feed_state.failure_streak</code>.
     */
    public Integer getFailureStreak() {
        return (Integer) get(5);
    }

    /**
     * Setter for
     * <code>stroom.shapeshifter_feed_state.error_mode_since_ms</code>.
     */
    public void setErrorModeSinceMs(Long value) {
        set(6, value);
    }

    /**
     * Getter for
     * <code>stroom.shapeshifter_feed_state.error_mode_since_ms</code>.
     */
    public Long getErrorModeSinceMs() {
        return (Long) get(6);
    }

    /**
     * Setter for <code>stroom.shapeshifter_feed_state.error_mode_reason</code>.
     */
    public void setErrorModeReason(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>stroom.shapeshifter_feed_state.error_mode_reason</code>.
     */
    public String getErrorModeReason() {
        return (String) get(7);
    }

    /**
     * Setter for <code>stroom.shapeshifter_feed_state.reset_time_ms</code>.
     */
    public void setResetTimeMs(Long value) {
        set(8, value);
    }

    /**
     * Getter for <code>stroom.shapeshifter_feed_state.reset_time_ms</code>.
     */
    public Long getResetTimeMs() {
        return (Long) get(8);
    }

    /**
     * Setter for <code>stroom.shapeshifter_feed_state.reset_user</code>.
     */
    public void setResetUser(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>stroom.shapeshifter_feed_state.reset_user</code>.
     */
    public String getResetUser() {
        return (String) get(9);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ShapeshifterFeedStateRecord
     */
    public ShapeshifterFeedStateRecord() {
        super(ShapeshifterFeedState.SHAPESHIFTER_FEED_STATE);
    }

    /**
     * Create a detached, initialised ShapeshifterFeedStateRecord
     */
    public ShapeshifterFeedStateRecord(Long id, Integer version, Long updateTimeMs, String docUuid, String feedName, Integer failureStreak, Long errorModeSinceMs, String errorModeReason, Long resetTimeMs, String resetUser) {
        super(ShapeshifterFeedState.SHAPESHIFTER_FEED_STATE);

        setId(id);
        setVersion(version);
        setUpdateTimeMs(updateTimeMs);
        setDocUuid(docUuid);
        setFeedName(feedName);
        setFailureStreak(failureStreak);
        setErrorModeSinceMs(errorModeSinceMs);
        setErrorModeReason(errorModeReason);
        setResetTimeMs(resetTimeMs);
        setResetUser(resetUser);
        resetTouchedOnNotNull();
    }
}
