/*
 * This file is generated by jOOQ.
 */
package stroom.shapeshifter.ai.impl.db.jooq.tables.records;


import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;

import stroom.shapeshifter.ai.impl.db.jooq.tables.ShapeshifterShape;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ShapeshifterShapeRecord extends UpdatableRecordImpl<ShapeshifterShapeRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>stroom.shapeshifter_shape.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>stroom.shapeshifter_shape.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>stroom.shapeshifter_shape.version</code>.
     */
    public void setVersion(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>stroom.shapeshifter_shape.version</code>.
     */
    public Integer getVersion() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>stroom.shapeshifter_shape.create_time_ms</code>.
     */
    public void setCreateTimeMs(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>stroom.shapeshifter_shape.create_time_ms</code>.
     */
    public Long getCreateTimeMs() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>stroom.shapeshifter_shape.update_time_ms</code>.
     */
    public void setUpdateTimeMs(Long value) {
        set(3, value);
    }

    /**
     * Getter for <code>stroom.shapeshifter_shape.update_time_ms</code>.
     */
    public Long getUpdateTimeMs() {
        return (Long) get(3);
    }

    /**
     * Setter for <code>stroom.shapeshifter_shape.doc_uuid</code>.
     */
    public void setDocUuid(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>stroom.shapeshifter_shape.doc_uuid</code>.
     */
    public String getDocUuid() {
        return (String) get(4);
    }

    /**
     * Setter for <code>stroom.shapeshifter_shape.shape_id</code>.
     */
    public void setShapeId(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>stroom.shapeshifter_shape.shape_id</code>.
     */
    public String getShapeId() {
        return (String) get(5);
    }

    /**
     * Setter for <code>stroom.shapeshifter_shape.given_up_reason</code>.
     */
    public void setGivenUpReason(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>stroom.shapeshifter_shape.given_up_reason</code>.
     */
    public String getGivenUpReason() {
        return (String) get(6);
    }

    /**
     * Setter for <code>stroom.shapeshifter_shape.relearn_reason</code>.
     */
    public void setRelearnReason(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>stroom.shapeshifter_shape.relearn_reason</code>.
     */
    public String getRelearnReason() {
        return (String) get(7);
    }

    /**
     * Setter for <code>stroom.shapeshifter_shape.awaiting_rule_uuid</code>.
     */
    public void setAwaitingRuleUuid(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>stroom.shapeshifter_shape.awaiting_rule_uuid</code>.
     */
    public String getAwaitingRuleUuid() {
        return (String) get(8);
    }

    /**
     * Setter for <code>stroom.shapeshifter_shape.rolling_score</code>.
     */
    public void setRollingScore(Double value) {
        set(9, value);
    }

    /**
     * Getter for <code>stroom.shapeshifter_shape.rolling_score</code>.
     */
    public Double getRollingScore() {
        return (Double) get(9);
    }

    /**
     * Setter for <code>stroom.shapeshifter_shape.rolling_records</code>.
     */
    public void setRollingRecords(Integer value) {
        set(10, value);
    }

    /**
     * Getter for <code>stroom.shapeshifter_shape.rolling_records</code>.
     */
    public Integer getRollingRecords() {
        return (Integer) get(10);
    }

    /**
     * Setter for <code>stroom.shapeshifter_shape.lease_node</code>.
     */
    public void setLeaseNode(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>stroom.shapeshifter_shape.lease_node</code>.
     */
    public String getLeaseNode() {
        return (String) get(11);
    }

    /**
     * Setter for <code>stroom.shapeshifter_shape.lease_expiry_ms</code>.
     */
    public void setLeaseExpiryMs(Long value) {
        set(12, value);
    }

    /**
     * Getter for <code>stroom.shapeshifter_shape.lease_expiry_ms</code>.
     */
    public Long getLeaseExpiryMs() {
        return (Long) get(12);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ShapeshifterShapeRecord
     */
    public ShapeshifterShapeRecord() {
        super(ShapeshifterShape.SHAPESHIFTER_SHAPE);
    }

    /**
     * Create a detached, initialised ShapeshifterShapeRecord
     */
    public ShapeshifterShapeRecord(Long id, Integer version, Long createTimeMs, Long updateTimeMs, String docUuid, String shapeId, String givenUpReason, String relearnReason, String awaitingRuleUuid, Double rollingScore, Integer rollingRecords, String leaseNode, Long leaseExpiryMs) {
        super(ShapeshifterShape.SHAPESHIFTER_SHAPE);

        setId(id);
        setVersion(version);
        setCreateTimeMs(createTimeMs);
        setUpdateTimeMs(updateTimeMs);
        setDocUuid(docUuid);
        setShapeId(shapeId);
        setGivenUpReason(givenUpReason);
        setRelearnReason(relearnReason);
        setAwaitingRuleUuid(awaitingRuleUuid);
        setRollingScore(rollingScore);
        setRollingRecords(rollingRecords);
        setLeaseNode(leaseNode);
        setLeaseExpiryMs(leaseExpiryMs);
        resetTouchedOnNotNull();
    }
}
