/*
 * This file is generated by jOOQ.
 */
package stroom.shapeshifter.ai.impl.db.jooq.tables.records;


import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;

import stroom.shapeshifter.ai.impl.db.jooq.tables.ShapeshifterOutput;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ShapeshifterOutputRecord extends UpdatableRecordImpl<ShapeshifterOutputRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>stroom.shapeshifter_output.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>stroom.shapeshifter_output.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>stroom.shapeshifter_output.create_time_ms</code>.
     */
    public void setCreateTimeMs(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>stroom.shapeshifter_output.create_time_ms</code>.
     */
    public Long getCreateTimeMs() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>stroom.shapeshifter_output.doc_uuid</code>.
     */
    public void setDocUuid(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>stroom.shapeshifter_output.doc_uuid</code>.
     */
    public String getDocUuid() {
        return (String) get(2);
    }

    /**
     * Setter for <code>stroom.shapeshifter_output.rule_uuid</code>.
     */
    public void setRuleUuid(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>stroom.shapeshifter_output.rule_uuid</code>.
     */
    public String getRuleUuid() {
        return (String) get(3);
    }

    /**
     * Setter for <code>stroom.shapeshifter_output.input_meta_id</code>.
     */
    public void setInputMetaId(Long value) {
        set(4, value);
    }

    /**
     * Getter for <code>stroom.shapeshifter_output.input_meta_id</code>.
     */
    public Long getInputMetaId() {
        return (Long) get(4);
    }

    /**
     * Setter for <code>stroom.shapeshifter_output.pipeline_uuid</code>.
     */
    public void setPipelineUuid(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>stroom.shapeshifter_output.pipeline_uuid</code>.
     */
    public String getPipelineUuid() {
        return (String) get(5);
    }

    /**
     * Setter for <code>stroom.shapeshifter_output.fragment_uuid</code>.
     */
    public void setFragmentUuid(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>stroom.shapeshifter_output.fragment_uuid</code>.
     */
    public String getFragmentUuid() {
        return (String) get(6);
    }

    /**
     * Setter for <code>stroom.shapeshifter_output.provisional</code>.
     */
    public void setProvisional(Boolean value) {
        set(7, value);
    }

    /**
     * Getter for <code>stroom.shapeshifter_output.provisional</code>.
     */
    public Boolean getProvisional() {
        return (Boolean) get(7);
    }

    /**
     * Setter for <code>stroom.shapeshifter_output.score</code>.
     */
    public void setScore(Double value) {
        set(8, value);
    }

    /**
     * Getter for <code>stroom.shapeshifter_output.score</code>.
     */
    public Double getScore() {
        return (Double) get(8);
    }

    /**
     * Setter for <code>stroom.shapeshifter_output.boundary_element</code>.
     */
    public void setBoundaryElement(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>stroom.shapeshifter_output.boundary_element</code>.
     */
    public String getBoundaryElement() {
        return (String) get(9);
    }

    /**
     * Setter for <code>stroom.shapeshifter_output.boundary_array</code>.
     */
    public void setBoundaryArray(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>stroom.shapeshifter_output.boundary_array</code>.
     */
    public String getBoundaryArray() {
        return (String) get(10);
    }

    /**
     * Setter for <code>stroom.shapeshifter_output.boundary_depth</code>.
     */
    public void setBoundaryDepth(Integer value) {
        set(11, value);
    }

    /**
     * Getter for <code>stroom.shapeshifter_output.boundary_depth</code>.
     */
    public Integer getBoundaryDepth() {
        return (Integer) get(11);
    }

    /**
     * Setter for <code>stroom.shapeshifter_output.produce_time_ms</code>.
     */
    public void setProduceTimeMs(Long value) {
        set(12, value);
    }

    /**
     * Getter for <code>stroom.shapeshifter_output.produce_time_ms</code>.
     */
    public Long getProduceTimeMs() {
        return (Long) get(12);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ShapeshifterOutputRecord
     */
    public ShapeshifterOutputRecord() {
        super(ShapeshifterOutput.SHAPESHIFTER_OUTPUT);
    }

    /**
     * Create a detached, initialised ShapeshifterOutputRecord
     */
    public ShapeshifterOutputRecord(Long id, Long createTimeMs, String docUuid, String ruleUuid, Long inputMetaId, String pipelineUuid, String fragmentUuid, Boolean provisional, Double score, String boundaryElement, String boundaryArray, Integer boundaryDepth, Long produceTimeMs) {
        super(ShapeshifterOutput.SHAPESHIFTER_OUTPUT);

        setId(id);
        setCreateTimeMs(createTimeMs);
        setDocUuid(docUuid);
        setRuleUuid(ruleUuid);
        setInputMetaId(inputMetaId);
        setPipelineUuid(pipelineUuid);
        setFragmentUuid(fragmentUuid);
        setProvisional(provisional);
        setScore(score);
        setBoundaryElement(boundaryElement);
        setBoundaryArray(boundaryArray);
        setBoundaryDepth(boundaryDepth);
        setProduceTimeMs(produceTimeMs);
        resetTouchedOnNotNull();
    }
}
